### ISSUE TITLE
Railroad syntax diagram

### ISSUE THREAD

**Issue by McCache** [mermaid-js/mermaid#4800] opened 2023-09-01 23:12 UTC
### Proposal

Mermaid.js should add Railroad syntax diagram for there isn't one implemented yet for Mermaid.

SEE: https://en.wikipedia.org/wiki/Syntax_diagram
SEE: https://github.com/tabatkins/railroad-diagrams

### Use Cases

This will greatly enhance our GitHub README.md for projects related to some kind of domain language that has a syntax.

### Implementation

None

**Comment by Yokozuna59** [comment] 2023-09-01 23:28
duplicate of #4252, and it's under development in #4608 by @nirname.

**Closed by Yokozuna59** 2023-09-01 23:28 UTC
Labels: Type: Enhancement, Status: Triage, Type: New Diagram
