### ISSUE TITLE
How to turned off autonumber via the diagram code as in the diagram? 8.8.3 delete autonumber is no effect

### ISSUE THREAD

**Issue by castlesnow** [mermaid-js/mermaid#1847] opened 2021-01-07 01:40 UTC

**Comment by GDFaber** [comment] 2021-01-23 23:03
Hi, you could try setting `showSequenceNumbers` to `true` or `false` in the configs, depending on what you need.
Please refer to the [sequenceDiagram documentation](https://mermaid-js.github.io/mermaid/#/sequenceDiagram?id=sequencenumbers) for further details.

**Comment by elf-pavlik** [comment] 2021-10-12 13:11
> Please refer to the [sequenceDiagram documentation](https://mermaid-js.github.io/mermaid/#/sequenceDiagram?id=sequencenumbers) for further details.

It states 

> It can also be be turned on via the diagram code as in the diagram:
```
sequenceDiagram
    autonumber
```

But now on seems to be default so there doesn't seem to be a way to turn it off via the diagram code.

**Comment by LuPro** [comment] 2021-12-08 01:22
I'm having a similar issue. Once I turn on autonumber using the diagram code it doesn't stop autonumbering no matter what I do (even setting `sequence: { showSequenceNumbers: false }` doesn't deactivate it).
I'm using mermaid from within Obsidian.md and when I restart the entire program the numbering goes away

The same behavior is seen on the [live edit page](https://mermaid-js.github.io/mermaid-live-editor/edit/) (also with reloading removing autonumber again).

This feels very much like a bug and not some feature I'm misunderstanding, but I'm happy to be corrected on that front :)

**Comment by Yash-Singh1** [comment] 2021-12-09 01:01
I can't reproduce on v8.13.4 on the live editor page:

[![](https://mermaid.ink/img/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgQWxpY2UtPj4rSm9objogSGVsbG8gSm9obiwgaG93IGFyZSB5b3U_XG4gICAgQWxpY2UtPj4rSm9objogSm9obiwgY2FuIHlvdSBoZWFyIG1lP1xuICAgIEpvaG4tLT4-LUFsaWNlOiBIaSBBbGljZSwgSSBjYW4gaGVhciB5b3UhXG4gICAgSm9obi0tPj4tQWxpY2U6IEkgZmVlbCBncmVhdCFcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgQWxpY2UtPj4rSm9objogSGVsbG8gSm9obiwgaG93IGFyZSB5b3U_XG4gICAgQWxpY2UtPj4rSm9objogSm9obiwgY2FuIHlvdSBoZWFyIG1lP1xuICAgIEpvaG4tLT4-LUFsaWNlOiBIaSBBbGljZSwgSSBjYW4gaGVhciB5b3UhXG4gICAgSm9obi0tPj4tQWxpY2U6IEkgZmVlbCBncmVhdCFcbiIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9)

**Comment by LuPro** [comment] 2021-12-09 01:06
https://user-images.githubusercontent.com/20774976/145315551-62f773a0-512b-46fe-bbdf-5e6de3b88a81.mp4

this is what happens for me every time I try. I'm on Firefox but I don't think that's the issue as Obsidian.md is an Electron app and I have the exact same issue there as well. Maybe it's the OS? Wouldn't know what the OS could do to cause this, but I'm on Linux Manjaro XFCE (I can also test Manjaro KDE and Windows 10 if you want/need me to)

**Comment by underscore-ex** [comment] 2022-02-04 03:37
Can confirm that this is happening in *Notion* app too which uses mermaid

**Comment by arisc097** [comment] 2022-04-18 22:28
we need way to reset the count similar to how plantuml offers.

**Comment by yubischiess** [comment] 2022-04-18 22:30
> we need way to reset the count similar to how plantuml offers.

i'd benefit from this as well - perhaps open a new issue / feature request?

**Comment by Yash-Singh1** [comment] 2022-04-18 22:35
Is this bug still a problem in v9.0.0 on https://mermaid.live/ ?

**Comment by mdeliw** [comment] 2022-04-19 04:00
> > we need way to reset the count similar to how plantuml offers.
> 
> i'd benefit from this as well - perhaps open a new issue / feature request?

Done https://github.com/mermaid-js/mermaid/issues/2952

**Comment by lxymtics** [comment] 2022-05-05 11:19
It also appeared in Typora. [Typora#5216](https://github.com/typora/typora-issues/issues/5216)

**Comment by doubler84** [comment] 2022-09-13 11:16
Also on GitLab Community Edition [13.12.2](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v13.12.2) autonumber is activaed by default :pensive:

**Comment by sidharthv96** [comment] 2023-09-16 09:04
Issue is fixed now in live editor. 

@doubler84 If autonumber is activated by default, you can try using the yaml config to set it to false. That should override the site config. 

The order of the configs applied are 
1. Default config
2. Site config
3. YAML/Directives
4. Diagram code

https://github.com/mermaid-js/mermaid/assets/10703445/6510be7c-d1ae-42f4-bb0b-efb87d206188

**Closed by sidharthv96** 2023-09-16 09:04 UTC
Labels: Type: Other, Graph: Sequence, Status: Triage, Type: Question
