### ISSUE TITLE
parse error with word `graph`

### ISSUE THREAD

**Issue by ThibaudLopez** [mermaid-js/mermaid#4079] opened 2023-02-10 04:41 UTC
### Description

There's a parse error with the word `graph` in a node text.

For example, all these combinations work correctly:
```
graph
    -
    A
    A-
    -A
    A-A
    graphA
    graphA-
    -graphA
    graphA-graphA
    Agraph
    Agraph-
    -Agraph
    Agraph-Agraph
    graphA-A
    A-graphA
    Agraph-A
    graphgraph
    graphgraphA
    Agraphgraph
    AgraphgraphA
    A-Agraph
    graphA-Agraph
    Agraph-graphgraph
    Agraph-graphA
    graphgraph-graphgraph
    graphgraph-graphA
    graphgraph-graphAgraph
    graphAAgraph
```

But any one of these combinations throws a parse error, even though the keyword `graph` is not a single word:
```
graph
    -graph
    graph-
    graph-A
    A-graph
    -graph-A
    A-graph-
    A-graph-A
    graph-graph
    graph-Agraph
    graphgraph-graph
    graphA-graph
    Agraph-graph
    graph-graphgraph
    graph-graphA
    graph-graphAgraph
```

### Steps to reproduce

Try in https://mermaid.live/

### Code Sample

```text
Try all combinations:

for (var a of ['', 'graph'])
for (var b of ['', 'A'])
for (var c of ['', 'graph'])
for (var d of ['', '-'])
for (var e of ['', 'graph'])
for (var f of ['', 'A'])
for (var g of ['', 'graph'])
console.log([a,b,c,d,e,f,g].join(''));
```

**Comment by ibrahimWassouf** [comment] 2023-07-16 03:45
This is also a duplicate of #2135, @nirname. Keywords are getting in the way as you said.

**Comment by nirname** [comment] 2023-07-16 11:05
@ibrahimWassouf May be it is, but this is related to a different part of grammar. Yes, this is all about keywords, but from users' perspective it is like an occurrence that is not related to other keywords. If you are going to fix it withing one PR - this is even better. Simply mark that your PR will resolve this as well

**Comment by nirname** [comment] 2023-07-16 12:32
Please refer to this one https://github.com/mermaid-js/mermaid/issues/2135, I am closing it, because they share similar problem

**Closed by nirname** 2023-07-16 12:32 UTC
Labels: Type: Bug / Error, Contributor needed, Status: Approved, Graph: Flow, Good first issue!
