### ISSUE TITLE
Crash when nested urly braces in class diagram

### ISSUE THREAD

**Issue by abnerlee** [mermaid-js/mermaid#1115] opened 2019-12-04 16:29 UTC
1. Go to https://mermaidjs.github.io/mermaid-live-editor
2. input 
```
classDiagram

class Person {
  Name {}
}
```
3. The page will be Not Responding

 - OS: macOS 10.15.1
 - Browser Chrome
 - Version 78

**Comment by Dunning-Kruger** [comment] 2019-12-04 16:34
@abnerlee Thank you for the report! Duplicate of #1069

**Closed by Dunning-Kruger** 2019-12-04 16:34 UTC
Labels: Status: Triage, Type: Bug / Error
