### ISSUE TITLE
Using "style" in node name causes parse error

### ISSUE THREAD

**Issue by kmuncie** [mermaid-js/mermaid#999] opened 2019-10-15 20:09 UTC
**Describe the bug**
Any usage of the word "style" in a node name causes a parsing error. This only happens when the word is lower case.

**To Reproduce**
- Create simple graph containing a node with style in it.
```
graph TD;
  a-style-project-name --> using-style-causes-parse-error
  style --> style2
```

[See in Mermaid Live Editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEQ7XG4gIGEtc3R5bGUtcHJvamVjdC1uYW1lIC0tPiB1c2luZy1zdHlsZS1jYXVzZXMtcGFyc2UtZXJyb3JcbiBzdHlsZSAtLT4gc3R5bGUyXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ/error/UGFyc2UgZXJyb3Igb24gbGluZSAyOgpncmFwaCBURDsgIGEtc3R5bGUtcHJvamVjdC1uYW1lIC0KLS0tLS0tLS0tLS0tLV4KRXhwZWN0aW5nICdTRU1JJywgJ05FV0xJTkUnLCAnU1BBQ0UnLCAnRU9GJywgJ1NRUycsICdTVFlMRV9TRVBBUkFUT1InLCAnUFMnLCAnKC0nLCAnRElBTU9ORF9TVEFSVCcsICdUQUdFTkQnLCAnVFJBUFNUQVJUJywgJ0lOVlRSQVBTVEFSVCcsICctLScsICdBUlJPV19QT0lOVCcsICdTVEFSVF9ET1VCTEVfQVJST1dfUE9JTlQnLCAnQVJST1dfQ0lSQ0xFJywgJ1NUQVJUX0RPVUJMRV9BUlJPV19DSVJDTEUnLCAnQVJST1dfQ1JPU1MnLCAnU1RBUlRfRE9VQkxFX0FSUk9XX0NST1NTJywgJ0FSUk9XX09QRU4nLCAnLS4nLCAnRE9UVEVEX0FSUk9XX1BPSU5UJywgJ1NUQVJUX0RPVUJMRV9ET1RURURfQVJST1dfUE9JTlQnLCAnRE9UVEVEX0FSUk9XX0NJUkNMRScsICdTVEFSVF9ET1VCTEVfRE9UVEVEX0FSUk9XX0NJUkNMRScsICdET1RURURfQVJST1dfQ1JPU1MnLCAnU1RBUlRfRE9VQkxFX0RPVFRFRF9BUlJPV19DUk9TUycsICdET1RURURfQVJST1dfT1BFTicsICc9PScsICdUSElDS19BUlJPV19QT0lOVCcsICdTVEFSVF9ET1VCTEVfVEhJQ0tfQVJST1dfUE9JTlQnLCAnVEhJQ0tfQVJST1dfQ0lSQ0xFJywgJ1NUQVJUX0RPVUJMRV9USElDS19BUlJPV19DSVJDTEUnLCAnVEhJQ0tfQVJST1dfQ1JPU1MnLCAnU1RBUlRfRE9VQkxFX1RISUNLX0FSUk9XX0NST1NTJywgJ1RISUNLX0FSUk9XX09QRU4nLCAnRE9VQkxFX0FSUk9XX1BPSU5UJywgJ0RPVUJMRV9BUlJPV19DSVJDTEUnLCAnRE9VQkxFX0FSUk9XX0NST1NTJywgJ0RPVUJMRV9ET1RURURfQVJST1dfUE9JTlQnLCAnRE9VQkxFX0RPVFRFRF9BUlJPV19DSVJDTEUnLCAnRE9VQkxFX0RPVFRFRF9BUlJPV19DUk9TUycsICdET1VCTEVfVEhJQ0tfQVJST1dfUE9JTlQnLCAnRE9VQkxFX1RISUNLX0FSUk9XX0NJUkNMRScsICdET1VCTEVfVEhJQ0tfQVJST1dfQ1JPU1MnLCAnRE9XTicsICdOVU0nLCAnQ09NTUEnLCAnQUxQSEEnLCAnQ09MT04nLCAnTUlOVVMnLCAnQlJLVCcsICdET1QnLCAnUFVOQ1RVQVRJT04nLCAnVU5JQ09ERV9URVhUJywgJ1BMVVMnLCAnRVFVQUxTJywgJ01VTFQnLCAnVU5ERVJTQ09SRScsIGdvdCAnU1RZTEUn)

**Expected behavior**
I expect to be able to use any word in the node name I want. If it is reserved there should be a way to escape it.

**Additional context**
Tested with `8.3.0`

**Comment by jgreywolf** [comment] 2019-11-12 00:41
Besides using upper case letters you can also remove the "punctuation" character (the `-`), or add another character to the beginning or end of the text "style".

Not great options, to be sure.
But just some things I noticed while investigating

**Comment by jgreywolf** [comment] 2019-11-26 23:58
I'm not sure that it is appropriate to handle this as a bug. Though It could be argued either way.  This is not just an issue with `style`, it's also an issue with ANY keywords used as a node name.

I would think that the fix for this would need to be at a broader scale than just making it possible to use `style` within a node name, etc.

Im guessing it is the same for other diagram types, though I have only tested a couple of cases with classDiagram

**Comment by kmuncie** [comment] 2019-11-27 00:06
> I'm not sure that it is appropriate to handle this as a bug. Though It could be argued either way. This is not just an issue with `style`, it's also an issue with ANY keywords used as a node name.

Yes, absolutely! As I noted in the original report, simply adding a mechanism for escaping reserved keywords would be the best universal fix in my opinion.

**Comment by heavysixer** [comment] 2019-12-04 18:59
I think this is a non issue. You can't do something like `let var = "foo"` in JavaScript, and the same case is true here. The issue is that conceptually mermaid has a textual visual model of the graph, which tends to make the reserved words _disappear_. My suggestion is to use some sort of naming convention like [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation) to bypass this problem.

**Comment by jgreywolf** [comment] 2020-08-12 17:58
I am closing this item as "by design" with the idea of not being able to use "reserved" keywords as node names. However, we may still look at providing a way to escape strings per issue #1506

**Closed by jgreywolf** 2020-08-12 17:58 UTC
Labels: Good first issue!, Help wanted!, Retained, Status: Approved, Type: Bug / Error
