### ISSUE TITLE
Class diagrams not support nested multiple generic parameters type

### ISSUE THREAD

**Issue by immortal-boy** [mermaid-js/mermaid#5000] opened 2023-10-31 08:27 UTC
### Description

When I write a class which has a member which type is `B<C, D<E,F>>` like this:
```
classDiagram
    class A {
      B~C, D~E, F~~ a
    }
```
The type become `B<C, D>E, F<> a`. How can I get a `B<C, D<E,F>>` type.

### Steps to reproduce

![mermaid_live_example](https://github.com/mermaid-js/mermaid/assets/26198753/d0d22988-4b7a-469c-89f0-d44f862b7c72)

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by sidharthv96** [comment] 2023-11-02 11:16
cc @jgreywolf

**Comment by jgreywolf** [comment] 2023-12-11 00:42
Duplicate of #4937

**Closed by jgreywolf** 2023-12-11 00:42 UTC
Labels: Type: Bug / Error, Status: Triage
