### ISSUE TITLE
Add control diagrams to Mermaid

### ISSUE THREAD

**Issue by g-berthiaume** [mermaid-js/mermaid#2668] opened 2022-01-26 13:55 UTC
**Describe the solution you'd like**
Add control diagrams to Mermaid.
Here's two examples:
![image](https://user-images.githubusercontent.com/19377511/151174300-b0733fff-d327-4277-b9f2-f55ac1539c32.png)

**Additional context**
[Control engineering](https://en.wikipedia.org/wiki/Control_engineering) is everywhere.
The ability to create control diagrams in the codebases documentation would facilitate communication with software teams.

**Comment by g-berthiaume** [comment] 2022-02-23 20:35
Related: https://github.com/mermaid-js/mermaid/issues/2768

**Comment by Foadsf** [comment] 2022-02-23 20:53
Hey @g-berthiaume you may also be interested in [this follow-up question on Reddit](https://www.reddit.com/r/controlengineering/comments/syjs2s/are_there_any_lightweight_markup_languages_to/?utm_source=share&utm_medium=web2x&context=3).

**Comment by jgreywolf** [comment] 2023-04-06 15:53
Closing as dupe of #2768

**Closed by jgreywolf** 2023-04-06 15:53 UTC
Labels: Type: Enhancement, Status: Triage
