### ISSUE TITLE
IE 11 unable to see flowcharts

### ISSUE THREAD

**Issue by AshokkumarPesarlanka** [mermaid-js/mermaid#1099] opened 2019-11-28 12:39 UTC
unable to see flowcharts in IE 11 windows 10 it was showing empty any alternative

**Comment by GDFaber** [comment] 2019-11-28 13:16
This issue seems to be connected to #1030 if you ask me.

**Comment by Dunning-Kruger** [comment] 2019-11-28 13:30
Closed as a duplicate of #1030. Thank you @GDFaber!

**Closed by Dunning-Kruger** 2019-11-28 13:30 UTC
Labels: Status: Triage, Type: Bug / Error
