### ISSUE TITLE
Strange Render Error with Chrome

### ISSUE THREAD

**Issue by laktak** [mermaid-js/mermaid#1806] opened 2020-12-03 16:25 UTC
**Describe the bug**

Chrome produces a strange render bug when running under Linux with HiDPI - see screenshot.

**To Reproduce**
1. Go to https://mermaid-js.github.io/mermaid-live-editor/

**Screenshots**
<img width="469" alt="Screen Shot 2020-12-03 at 17 14 21" src="https://user-images.githubusercontent.com/959858/101057230-1e00e200-358c-11eb-891f-6a78e289c4fe.png">

**Desktop (please complete the following information):**
 - OS: Linux, Arch
 - Browser: Chromium
 - Version: 87

**Additional context**
The live editor renders fine with Firefox on the same system or with Chrome in Windows or with Safari.

**Comment by reinh** [comment] 2021-02-03 22:46
Also seeing this on MacOS 10.15.6, Chrome `Version 88.0.4324.96 (Official Build) (x86_64)`.

**Comment by rodolfoberrios** [comment] 2021-03-03 13:10
Also seeing this on:

* Ubuntu 20.04, Chrome `Version 88.0.4324.182 (Official Build) (64-bit)`.
* Android 10, Chrome `Version 88.0.4324.181`.

Doesn't affect Firefox in any of those.

**Comment by Yokozuna59** [comment] 2023-07-23 19:18
For this [comment](https://github.com/mermaid-js/mermaid/issues/1834#issuecomment-804796350):

> Works for me now in both Chrome and Edge v89.

And it's duplicate of #1834

**Closed by Yokozuna59** 2023-07-23 19:18 UTC
Labels: Type: Bug / Error, Graph: Flow, Status: Triage
