### ISSUE TITLE
Flowchart node spacing doesn't apply when using subgraph

### ISSUE THREAD

**Issue by danimihalca** [mermaid-js/mermaid#3258] opened 2022-07-25 07:32 UTC
I want to render some flowchart diagrams in a compact way to be readable on mobile, and found out that you can specify some distances between nodes using **nodeSpacing** (and **rankSpacing**), but it seems that when you start defining the nodes in a subgraph, it won't apply anymore.

1. Scenario 1 - nodes without subgraphs:
a) node spacing 10:

```
%%{init:{'flowchart':{'nodeSpacing': 10}}}%%

flowchart LR

A --> B
C --> D
```

[![](https://mermaid.ink/img/pako:eNo9jLEKwjAURX8lPAhdWtA1g6DWzcmub3kksQ02LyWmiIT8u1HU7Rzu4WbQwVhQIGV27JLKzXUODz1RTE0VruuwkHY8NkpsN6UUKZGR_5U4X96-F123Ewfk4wd6aMHb6MmZep6RhUBIk_UWQVU0FG8IyKV262Io2ZNxKURQV5rvtgVaUxierEGluNpf1DsaI_lvVV5lRD-m)](https://mermaid.live/edit#pako:eNo9jLEKwjAURX8lPAhdWtA1g6DWzcmub3kksQ02LyWmiIT8u1HU7Rzu4WbQwVhQIGV27JLKzXUODz1RTE0VruuwkHY8NkpsN6UUKZGR_5U4X96-F123Ewfk4wd6aMHb6MmZep6RhUBIk_UWQVU0FG8IyKV262Io2ZNxKURQV5rvtgVaUxierEGluNpf1DsaI_lvVV5lRD-m)

b) node spacing 50:

```
%%{init:{'flowchart':{'nodeSpacing': 50}}}%%

flowchart LR

A --> B
C --> D
```

[![](https://mermaid.ink/img/pako:eNo9jLEKwjAURX8lPAhdWnBxySCodXOy61seSWyDzUuJKSIh_24UdTuHe7gZdDAWFEiZHbukcnOdw0NPFFNThes6LKQdj40S200pRUpk5H8lzpe370XX7cQB-fiBHlrwNnpypp5nZCEQ0mS9RVAVDcUbAnKp3boYSvZkXAoR1JXmu22B1hSGJ2tQKa72F_WOxkj-W5UXZ4Q_qg)](https://mermaid.live/edit#pako:eNo9jLEKwjAURX8lPAhdWnBxySCodXOy61seSWyDzUuJKSIh_24UdTuHe7gZdDAWFEiZHbukcnOdw0NPFFNThes6LKQdj40S200pRUpk5H8lzpe370XX7cQB-fiBHlrwNnpypp5nZCEQ0mS9RVAVDcUbAnKp3boYSvZkXAoR1JXmu22B1hSGJ2tQKa72F_WOxkj-W5UXZ4Q_qg)

Renders well, the nodes are properly spaced.

2. Scenario 2, node within subgraphs:
a) node spacing 10:

```
%%{init:{'flowchart':{'nodeSpacing': 10, 'rankSpacing':'10'}}}%%

flowchart LR

X --> Y
subgraph X
	direction LR
	A
	C
end

subgraph Y
	direction LR
	B
	D
end
```

[![](https://mermaid.ink/img/pako:eNptj0GLwjAQhf9KGCi5VNBrDoK77s2TXlrIZUxGG7STEqeIlPx3U3dXWNjL472Zb3jMBC56AgNVNQUOYiZ9usa76zCJLoHL9jCgC3zWRq2WtdIJ-fIe6dVS55yryrLl96Xa7efcqMVirdrZ3sbjOeHQqaYk8SGRkxD5G5TNLJ-Wif0fuP0P_phl-4Khhp5Sj8GXDybLSlmQjnqyYIr1mC4WLOfCjYNHoS8fJCYwJ7zeqAYcJR4e7MBIGukX2gYs9f0PlZ-g7WYW)](https://mermaid.live/edit#pako:eNptj0GLwjAQhf9KGCi5VNBrDoK77s2TXlrIZUxGG7STEqeIlPx3U3dXWNjL472Zb3jMBC56AgNVNQUOYiZ9usa76zCJLoHL9jCgC3zWRq2WtdIJ-fIe6dVS55yryrLl96Xa7efcqMVirdrZ3sbjOeHQqaYk8SGRkxD5G5TNLJ-Wif0fuP0P_phl-4Khhp5Sj8GXDybLSlmQjnqyYIr1mC4WLOfCjYNHoS8fJCYwJ7zeqAYcJR4e7MBIGukX2gYs9f0PlZ-g7WYW)

b) node spacing 50:

```
%%{init:{'flowchart':{'nodeSpacing': 50, 'rankSpacing':'10'}}}%%

flowchart LR

X --> Y

subgraph X
	direction LR
	A
	C
end

subgraph Y
	direction LR
	B
	D
end
```
[![](https://mermaid.ink/img/pako:eNptjz-LwzAMxb-KEQQvKbTDLR4K_bd1ui4teFFttTFp5OAqHEfwd6_TuxYObnm8J_3EQyO46AkMVNUYOIgZ9eUWv1yDSXQJXLaHHl3gqzbqY14rnZDb90gv5jrnXFWWLb8v1f5zykc1my3VabL34XxN2DfqWJL4kMhJiPwDymqSjWVi_wc-_QevJ9k-Yaiho9Rh8OWD0bJSFqShjiyYYj2m1oLlXLih9yi080FiAnPB251qwEHi4ZsdGEkDvaBtwFLf_VL5AaTBZho)](https://mermaid.live/edit#pako:eNptjz-LwzAMxb-KEQQvKbTDLR4K_bd1ui4teFFttTFp5OAqHEfwd6_TuxYObnm8J_3EQyO46AkMVNUYOIgZ9eUWv1yDSXQJXLaHHl3gqzbqY14rnZDb90gv5jrnXFWWLb8v1f5zykc1my3VabL34XxN2DfqWJL4kMhJiPwDymqSjWVi_wc-_QevJ9k-Yaiho9Rh8OWD0bJSFqShjiyYYj2m1oLlXLih9yi080FiAnPB251qwEHi4ZsdGEkDvaBtwFLf_VL5AaTBZho)

Node spacing doesn't apply anymore when these nodes are inside subgraph, the vertical distance between them remains the same.

Expected: To be able to apply node spacing inside a subgraph as well.
Environment: Latest Mermaid Live Editor (9.1.3), Obsidian 0.5.18 (don't know what Mermaid version they're using, but mentioning it here since there I found it first).

**Comment by sketchkey** [comment] 2022-09-05 08:11
Bump! This is also the case for rankSpacing within subgraphs — subgraph spacing just seems to revert back to the default.

**Comment by varon** [comment] 2022-09-13 19:11
I have also encountered this error.

**Comment by varon** [comment] 2022-09-13 19:37
Same problem. This would be great to fix.

**Comment by natbusa** [comment] 2022-11-07 07:43
RankSpacing and NodeSpacing are not passed to subgraphs. Confirmed

**Comment by jonagard** [comment] 2023-05-23 19:03
I hit this and noticed something in the behavior I thought should be recorded here.

First, I'm taking your exact example above and I get this on mermaid.live:  [mermaid link](https://mermaid.live/view#pako:eNptkDFrAzEMhf-KERxeLpCsHgJNM7ZLsySgRbXVnElPPlwdIRz-7_El5KYuQu_pe0hoAp8Cg4OmmaJEdZP9-U1X31FWW4XU6WEgH-VsndmsW2MzyWWx7GZtSylNg4KyJM3H16yPZrXamhPK3_h9zjR05lhtDTGz15jkienbXN5RWMKcWuDTf_BuLvsHDC30nHuKod4_oRiDoB33jOBqGyhfEFBK5WjUdLiJB6d55BbGIZDyPlLd1L9MDlFT_nz-4_GWcgf55GP3):

![Original](https://imgur.com/vvFeAbr)

I found that if you do a link from an internal node to an internal node in another subgraph, the spacing is acknowledged.  I took your code and just added a link from B to A:

```
%%{init:{'flowchart':{'nodeSpacing': 10, 'rankSpacing':'10'}}}%%

flowchart LR

X --> Y
subgraph X
	direction LR
	A
	C
end

subgraph Y
	direction LR
	B --> A
	D
end
```

And I get this in mermaid:  [mermaid link](https://mermaid.live/view#pako:eNptUMFqwzAM_RUjCL6k0F59KHTrcbuslxZ0UW2tMV3k4CmMEfzvdVKW0y5C7-k9Cb0JfAoMDppmihLVTfbzK_34jrLaCqROTwP5KDfrzG7bGptJ7itld1tbSmkaFJTVad4-Znw2m83eXFC-x-st09CZc6U1xMxeY5KnTA9zeUVhCbNrFV_-E78sOxfLcbFACz3nnmKoX0woxiBoxz0juNoGyncElFJ1NGo6_YoHp3nkFsYhkPIxUr3X_5Ecoqb8_kxlCac8AO6DZRA) now:

![with link](https://imgur.com/rltAi40)

I don't know what that implies, but it may help indicate what the root of the issue is.

**Comment by bigNeoneo** [comment] 2023-12-21 03:00
any good news?

**Comment by rowanfr** [comment] 2024-01-06 10:31
My apologies, I meant to close the issue #5178 as duplicate and instead accidentally closed it implying solved. This comment is to clarify that the issue with flowchart spacing has not been solved yet

**Closed** 2024-03-23 12:09 UTC
Labels: Type: Bug / Error, Status: Triage, roadmap

**Comment by bernardoadc** [comment] 2024-08-29 21:09
I didn't find the documentation, but have you guys noticed that in the example nodeSpacing is a number and rankSpacing is a string? Don't know if it is relevant.. but thought it was worth pointing it out.
