### ISSUE TITLE
ClassDiagram static fields end with $ not rendered in underlined style

### ISSUE THREAD

**Issue by lethefrost** [mermaid-js/mermaid#5182] opened 2024-01-06 19:36 UTC
I found the post here describing some similar issue in 2022

> For some reason, this currently only works in specific cases:
> ```mermaid
> classDiagram
>   class Person {
>   String name$
>   name : String$
>   name$ : String
>   name$
>   }
>   Person: int age$
>   Person: age$
> ```
> ```
> classDiagram
>   class Person {
>     String name$
>     name : String$
>     name$ : String
>     name$
>   }
>   Person: int age$
>   Person: age$
> ```
> 
> Why doesn't it just check, if the line is a field and ends with a `$` or `*`? It currently seems to do some shenanigans, that only allows it to work if the field is formatted in a specific way: 
First Character may be one of `+` `#` `-` `~`, one word without any special character, a whitespace, one word without any special character, ends with `$` or `*`
As RegEx something like this: `(\+|-|~|#)?[a-zA-Z0-9] [a-zA-Z0-9](\$|\*)`
>
> It should be more like this: `.*(\$|\*)`

_Originally posted by @Dampfwalze in https://github.com/mermaid-js/mermaid/issues/2269#issuecomment-1132783085_
            
---
 
Now in the latest version none of those form of representing a member variable will be correctly underlined. See the screenshot in the live editor:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/47198693/294713366-79eb4ecf-38c4-4f5c-8b93-e350ce8d40d3.png">

And any line with brackets will be considered as a method and can correctly identify the static `$` classifier. Since here in the [documentation](https://mermaid.js.org/syntax/classDiagram.html#defining-members-of-a-class) it still says 

> note you can also include additional classifiers to a field definition by adding the following notation to the very end:
> `$` Static e.g.: `String someField$`

I believe the unrecognized fields might not be the intended behavior?

**Comment by jgreywolf** [comment] 2024-01-17 17:01
I will take a look at this.  This should have been fixed with #5009

**Comment by jgreywolf** [comment] 2024-01-22 17:28
I cannot reproduce this.  The styles are applied for both fields and mermaids, as detailed in documentation here. The last character is used to denote static or abstract:
![image](https://github.com/mermaid-js/mermaid/assets/300077/08dc16b2-d187-40b7-a53b-e87f0c3df8ce)

**Comment by jgreywolf** [comment] 2024-01-27 20:03
![image](https://github.com/mermaid-js/mermaid/assets/300077/3061b257-1858-436f-a275-4308cbeae6ee)

[Also see at link](https://mermaid.ink/img/pako:eNpNkE9rxCAQxb-KDHu0S_5n9dxrobC34mWIs6kQdTEGug357o1JuqyH8c3vyXN0hs5rAgndgOP4brAPaJVjbOvZJ4XROzYnwtg1BuN65tDSaSdJMnkYL-z0hC8sySWVPVUy4yLDfjf-WeqBg6Vg0eh1sO1uBfGbLCmQq9R0w2mICpRb1qM4RX99uA7kDYeROEx3jZGOtzzpHR3IGX5AiuacFU2VF6IpL02bCw4PkG_ZOUurLUUm2lrURV5dqrKtFw6_3q9BOQfSJvrwcXxZ2rbgr82PYaLlD5BmaEo?type=png)](https://mermaid.live/edit#pako:eNpNkE9rxCAQxb-KDHu0S_5n9dxrobC34mWIs6kQdTEGug357o1JuqyH8c3vyXN0hs5rAgndgOP4brAPaJVjbOvZJ4XROzYnwtg1BuN65tDSaSdJMnkYL-z0hC8sySWVPVUy4yLDfjf-WeqBg6Vg0eh1sO1uBfGbLCmQq9R0w2mICpRb1qM4RX99uA7kDYeROEx3jZGOtzzpHR3IGX5AiuacFU2VF6IpL02bCw4PkG_ZOUurLUUm2lrURV5dqrKtFw6_3q9BOQfSJvrwcXxZ2rbgr82PYaLlD5BmaEo)

**Comment by sidharthv96** [comment] 2024-02-03 06:00
Github uses

```mermaid
info
```

**Closed by sidharthv96** 2024-02-03 06:00 UTC
Labels: Status: Triage
