### ISSUE TITLE
Flowchart shapes do not resize to the text correctly

### ISSUE THREAD

**Issue by ViezeVingertjes** [mermaid-js/mermaid#1790] opened 2020-11-25 08:35 UTC
It only seems to be with flowchart, all the other types are rendering correctly. 

Trying to dig deeper, it doesnt seem to correlate to a specific version though... I went back as far as 8.6.4 and it didnt fix it and i'm sure it did work correctly before. 

The only thing i can think of now, is that something changed with an update of the browsers? Windows itself? as it's globally on this system. More people should have this issue right?

**Describe the bug**
Flowchart shapes do not resize to the text correctly

**Expected behavior**
Text should be contained by the shapes.

**Screenshots**
![mermaid-bug](https://user-images.githubusercontent.com/10432760/100202342-7a676000-2f01-11eb-9bfc-56c9dea9c29d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome / Edge (Probably not browser specific)

**Comment by saketcap** [comment] 2020-11-25 13:52
Yep. I'm seeing the same issue. In my case it seems to happen in Microsoft Edge (Chromium) but not in Google Chrome.

**OS:** Windows 10 Pro v 1909 (Build: 18363.1198)
**MS Edge Chromium:** Version 87.0.664.41 (Official build) (64-bit)
**Google Chome:**  Version 86.0.4240.198 (Official Build) (64-bit)

MS Edge Chromium:

![image](https://user-images.githubusercontent.com/25690061/100235831-2b372480-2f2d-11eb-974a-9d8ec6eabc67.png)

Google Chrome:

![image](https://user-images.githubusercontent.com/25690061/100236008-646f9480-2f2d-11eb-8355-70cc1368e267.png)

**Comment by knsv** [comment] 2020-11-26 17:37
Hi Thanks for reporting! Could you please check your browsers zoom level.

**Comment by ViezeVingertjes** [comment] 2020-11-26 18:34
No problem, in my case, zoom level is at 100% (default). 
In the meantime, i did discover by accident that using `flowchart` instead of using `graph` does seem to fix it in our case.

**Comment by mohamed-seada-1994** [comment] 2020-11-29 10:30
I don't know the exact reason.
I noted this problem after updating chrome or edge to version 87
no problem in version 86

**Comment by saketcap** [comment] 2020-11-29 13:55
> Hi Thanks for reporting! Could you please check your browsers zoom level.

Thanks for responding!
I switched through various zoom levels (including at 100%) and it made no difference.

**Comment by jlixi** [comment] 2020-12-01 23:21
Hi, I am having the same issue using chrome Version 87.0.4280.66 (Official Build) (64-bit)

Changing the zoom level has no impact. However, I have found that the issue only occurs on high-resolution monitors.

**Comment by AndyCross** [comment] 2021-01-14 11:43
Echoing jlixi, on my primary (high-resolution) display I get the issue described. Moving to a secondary monitor and re-rendering causes the correct resizing of shapes. It is only on re-rendering on the new screen that things change. 

![image](https://user-images.githubusercontent.com/773613/104586631-a085c280-565d-11eb-9c3b-49ad0558e72f.png)
![image](https://user-images.githubusercontent.com/773613/104586675-b0050b80-565d-11eb-8080-f51db75c9b97.png)

**Comment by SuTanTank** [comment] 2021-01-29 04:08
I have the same issue with Chromium Edge, on both mac and windows. 
When the default zoom level is not 100%, the shapes are smaller than what they should be. Even adjust zoom level afterwards doesn't help. 
Resetting the default zoom back to 100% will fix this problem.

**Comment by slokhorst** [comment] 2021-02-11 21:44
On my 2x HiDPI screen, the rendering is incorrect at 100% scale, but correct at 50% scale. There seems to be a mix up between device pixels/physical pixels and CSS/SVG pixels somewhere.

**Comment by slokhorst** [comment] 2021-02-11 21:56
Perhaps related to https://chromium.googlesource.com/chromium/src/+/39b03b2e690ecca95d625f1138f8eec5e13f0a0e ?

**Comment by slokhorst** [comment] 2021-03-22 19:47
It seems that this issue was fixed in Chromium 89. Can anyone confirm?

**Comment by AndyCross** [comment] 2021-03-22 20:04
My above example no longer occurs, so thumbs up from me.

**Comment by jlixi** [comment] 2021-03-28 23:02
Hi, yes the issue is fixed for me too.

**Comment by Yokozuna59** [comment] 2023-07-23 19:13
For this [comment](https://github.com/mermaid-js/mermaid/issues/1790#issuecomment-804347039) 

> It seems that this issue was fixed in Chromium 89.

And it's duplicate of #1834.

**Closed by Yokozuna59** 2023-07-23 19:13 UTC
Labels: Type: Bug / Error, Graph: Flow, Status: Triage
