### ISSUE TITLE
Can mermaid support line graphs and interval graphs?

### ISSUE THREAD

**Issue by Horuyuki** [mermaid-js/mermaid#3537] opened 2022-09-30 16:09 UTC
**Is your feature request related to a problem? Please describe.**
I would like to put down graphs on the XY plain.
Like desmos, it will take an equation input or connecting points input (xy pair)

**Describe the solution you'd like**
Just a new chart diagram type within the current markdown block.

**Describe alternatives you've considered**
I have looked at obsidian-charts but would prefer a native solution more.

**Additional context**
![this](https://i.imgur.com/bSqgEo3.png)

**Comment by reregaga** [comment] 2022-10-02 15:05
Now Mermaid doesnt support plotting.

Similar requests https://github.com/mermaid-js/mermaid/discussions/3522 https://github.com/mermaid-js/mermaid/issues/2352#issuecomment-1197399209

**Comment by jgreywolf** [comment] 2023-01-26 20:02
Closing as duplicate of #2532 (since it is currently assigned)

**Closed by jgreywolf** 2023-01-26 20:02 UTC
Labels: Type: Enhancement, Status: Triage

**Comment by bespokecomp** [comment] 2023-07-19 16:20
> Now Mermaid doesnt support plotting.
> 
> Similar requests #3522 [#2352 (comment)](https://github.com/mermaid-js/mermaid/issues/2352#issuecomment-1197399209)

That's unfortunate.
May I ask why not, has it been taken away?
