### ISSUE TITLE
Misleading error messages displayed when entering data

### ISSUE THREAD

**Issue by JESii** [mermaid-js/mermaid#3852] opened 2022-11-26 03:22 UTC
**Describe the bug**
While entering data into the code block, error messages display that are misleading. In this example, I've just entered one line: `classDiagram` and pressed enter to go to a new line. It's not at all clear what the error message displayed below is trying to tell: is there an error on line 1? That is exactly what the error message is saying -- that there is an error at the end of line 1, immediately after the word `classDiagram`. Even if the error is on line two, what am I supposed to do with all that information.

**To Reproduce**

1. Goto to live editor & reset any code lines
2. Enter 'classDiagram<ENTER>`
3. Notice that you are on line 2 of the code editor
4....and the error shows that the error is at the end of line 1

**Expected behavior**
At this point there is no error to report, IMO... there really is only an error when I've completed entering a line. Only then can the live editor fully parse a statement. And I don't think that there is an error on line 1, anyway. Once I enter A -- B on line 2, then it clearly accepts the first line.

**Screenshots**
<img width="1353" alt="CleanShot 2022-11-25 at 07 49 48@2x" src="https://user-images.githubusercontent.com/486/204070238-bd35c087-3b8a-4790-b659-04ac398e2e18.png">

And once I enter the next line, then there is no error on line 1
<img width="1364" alt="CleanShot 2022-11-25 at 19 22 22@2x" src="https://user-images.githubusercontent.com/486/204070642-94433019-7642-41a5-b2ea-56f5e5881d63.png">

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS, big Sur
- Browser [e.g. chrome, safari] Chrome latest
- Version [e.g. 22] V9.2.2

**Additional context**
I've encountered several such misleading error messages which sent me down a rabbit hole. Maybe that's my issue, but I do think character-by-character parsing attempts (at least that's what it looks like it's doing) don't really help the end user.

Great product... thanks much!

**Comment by sidharthv96** [comment] 2022-11-26 03:59
Thanks @JESii!
Transferring it here as this is where the errors are generated from.

**Comment by JESii** [comment] 2022-11-26 06:07
Whew... I thought for a moment that I'd entered the bug ticket in the wrong place :=))

**Comment by jgreywolf** [comment] 2023-01-26 17:21
Closing as duplicate of #3853

**Closed by jgreywolf** 2023-01-26 17:21 UTC
Labels: Status: Triage, bug
