### ISSUE TITLE
Comment %% does not work on class diagram method

### ISSUE THREAD

**Issue by h33linL** [mermaid-js/mermaid#2307] opened 2021-09-12 01:47 UTC
```%%this is a comment``` works after variable, but doesn't work after class method in the class diagram.

I reproduced the issue on live editor, [ please check this](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5cbmNsYXNzIEJhcjEge1xuLWludCBtZW1iZXIgJSV0aGlzIGlzIGEgY29tbWVudFxuK21lbWJlcigpIGludFxufVxuXG5jbGFzcyBCYXIyIHtcbi1pbnQgbWVtYmVyXG4rbWVtYmVyKCkgaW50ICUldGhpcyBpcyBhIGNvbW1lbnRcbn1cbiIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOnRydWUsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjp0cnVlfQ)

```
classDiagram

class Bar1 {
-int member %%this is a comment
+member() int
}

class Bar2 {
-int member
+member() int %%this is a comment
}
```

I can see Bar1 gets created fine but for Bar2, the spot should show ```+member():int``` is showing ```this is```

**Comment by 64kramsystem** [comment] 2021-09-12 19:45
This'd be very convenient to have, as currently the other way to document a class is above the class definition.

Comments are also not allowed in their own line (inside a class) - I don't know if this is intended or the same bug:

```mermaid
class MyActor {
  children
  %% my comment on draw()
  draw()
  update()
}
```

**Comment by AltarBeastiful** [comment] 2021-09-13 07:30
@jgreywolf Is this linked to #1645 ?

**Comment by jgreywolf** [comment] 2023-01-26 20:25
Closing as duplicate of #1645

**Closed by jgreywolf** 2023-01-26 20:25 UTC
Labels: Type: Bug / Error, Status: Triage
