### ISSUE TITLE
add a "<--" symbol pointing from the right to the left 

### ISSUE THREAD

**Issue by yangeos** [mermaid-js/mermaid#4336] opened 2023-04-23 17:20 UTC
### Proposal

How about adding a 
<-- arrow to make the right to left pointing ??

### Example

a <-- b
will be rendered like
[a]<--[b]

**Comment by sidharthv96** [comment] 2023-04-23 17:35
```mermaid
flowchart LR
  a --> b
  b --> a
```

Currently, left pointing arrows are possible by switching the nodes. 

Can you share a scenario where `<--` would be useful?

**Comment by tomperr** [comment] 2023-04-29 21:45
Duplicate of #3208

**Comment by jgreywolf** [comment] 2023-05-25 22:54
Closing as duplicate

**Closed by jgreywolf** 2023-05-25 22:54 UTC
Labels: Type: Enhancement, Status: Triage
