### ISSUE TITLE
Multiple tasks on one line

### ISSUE THREAD

**Issue by Barry1** [mermaid-js/mermaid#1996] opened 2021-04-23 08:31 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes too many tasks makes the diagram difficult to read as it gets too long.

**Describe the solution you'd like**
I'd like to be able to print multiple task in one line.

**Describe alternatives you've considered**
Putting the tasks (the classical/only) way under earch other. The diagramm gets too long.

**Additional context**
A similiar solution is available in **plantuml** see [plantuml gantt examples](https://plantuml.com/de/gantt-diagram#:~:text=taskB%5D-,displays%20on%20same%20row,-as). See taskA and taskB in the following image

![image](https://user-images.githubusercontent.com/230051/115843291-f61cf880-a41e-11eb-8c5e-38259ef42fb4.png)

**Comment by Zachu** [comment] 2021-04-30 09:02
I think this is duplicate of https://github.com/mermaid-js/mermaid/issues/1813. But yeah I do agree with this one. Would be awesome feature.

My use-case is to create a vacation chart and would want each person to have only one line instead of multiple.

**Comment by aniston** [comment] 2021-11-24 13:54
Hi, I'm after this as well !

my2ct:
a bruteforce attempt via mangling the css (albeit after it's rendered !) using the dev console F12, in the browser, makes it's possible to bring tasks on one line, ie: manuplating the "y" position directly.
-  That said, I see there is a class `class="task crit0 "` being used at the end of the .html line. Anyone know how/if this [mermaid/gantt.md](https://github.com/mermaid-js/mermaid/blob/develop/docs/gantt.md#styling) can help workaround the "styling" to achieve a similar effect ?

`<rect id="b1" rx="3" ry="3" x="75" y="74" width="87" height="20" transform-origin="118.5px 84px" class="task crit0 "</rect>`

**Comment by fdventura** [comment] 2022-05-13 13:49
> I think this is duplicate of #1813. But yeah I do agree with this one. Would be awesome feature.
> 
> My use-case is to create a vacation chart and would want each person to have only one line instead of multiple.

I have precisely the same ask.

**Comment by aniston** [comment] 2023-06-27 22:09
@Zachu @fdventura in the current ver 10.2.3 this seems possible with a new mode in Gantt called [compact ](https://mermaid.js.org/syntax/gantt.html#output-in-compact-mode)mode.

**Comment by Yokozuna59** [comment] 2023-07-29 17:10
duplicate of #1813.

> You could have that layout using [compact mode](https://mermaid.js.org/syntax/gantt.html#output-in-compact-mode).
> https://github.com/mermaid-js/mermaid/issues/1813#issuecomment-1656791447

**Closed by Yokozuna59** 2023-07-29 17:10 UTC
Labels: Type: Enhancement, Graph: Gantt, Status: Triage
