### ISSUE TITLE
Dependency on github lib dagrejs/dagre-d3

### ISSUE THREAD

**Issue by damiandennis** [mermaid-js/mermaid#1071] opened 2019-11-18 04:05 UTC
Hey,

Could we possibly get the dependency changed from a github repo to an rpm lib "dagrejs/dagre-d3".
The main reason I am having issues with this is I am behind a corporate firewall and we have an internal repo for npm but nothing that caters for github dependencies. I hope this is not a big ask.

Thanks

**Comment by chris579** [comment] 2019-11-18 06:31
Duplicate of #1065

**Closed by chris579** 2019-11-18 06:31 UTC
Labels: Status: Triage
