### ISSUE TITLE
Diagram rendering is cut

### ISSUE THREAD

**Issue by JonathanPlasse** [mermaid-js/mermaid#1327] opened 2020-03-31 09:29 UTC
Hi,
I love mermaid, thank you.

I had a problem with this code
```
graph TD
	a --> b
	b --> a
	c --> b
	a --> c
```
In the live editor, the rendering is cut

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcblx0YSAtLT4gYlxuXHRiIC0tPiBhXG5cdGMgLS0-IGJcblx0YSAtLT4gY1xuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcblx0YSAtLT4gYlxuXHRiIC0tPiBhXG5cdGMgLS0-IGJcblx0YSAtLT4gY1xuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

**Comment by spopida** [comment] 2020-03-31 17:04
I think this is the same problem as in #1288.  I think the problem is this:  the layout engine seems to position the first vertex such that its top left corner will be close to the origin, allowing for any padding.  So if there is no padding, then the TL corner would be at 0,0.  Then, IF it needs to draw edges to left of this, some of the x co-ordinates in the edge paths will be *negative*.  This is fine, but near the end of the draw() function, the viewBox is set to start at 0,0 - this is a problem if the content contains negative co-ordinates.  In fact the solution might be as simple as setting the viewBox x and y to the svgBounds.x and svgBounds.y instead of 0,0.  I had the exact same problem a few days ago when implementing ER diagram, and fixed it like this.  You can assign this to me and I will give it a go.

**Closed** 2020-04-04 03:54 UTC
Labels: Status: Triage, Type: Bug / Error
