### ISSUE TITLE
Node names with special  characters that break syntax

### ISSUE THREAD

**Issue by yuanyazhen** [mermaid-js/mermaid#2388] opened 2021-10-09 10:50 UTC
**Details**
I tried to generate a graph for my project, but the node ID that came from the project path made something wrong.

The mermaid text that I was using

```
flowchart LR
src/report/dot/default-index.js[default-index.js] --> src/report/dot/dot.template.js[dot.template.js]
src/report/dot/index.js[index.js] --> src/report/dot/module-utl.js[module-utl.js]
```

Result came from mermaid editor

<img src="https://user-images.githubusercontent.com/13688619/136654485-a4ae4040-615d-4960-9301-c219200ea241.png" width="400" />

```
Parse error on line 2:
...LR  src/report/dot/default-index.js[def
----------------------^
Expecting 'SEMI', 'NEWLINE', 'SPACE', 'EOF', 'SQS', 'AMP', 'STYLE_SEPARATOR', 'PS', '(-', 'STADIUMSTART', 'SUBROUTINESTART', 'CYLINDERSTART', 'DIAMOND_START', 'TAGEND', 'TRAPSTART', 'INVTRAPSTART', 'START_LINK', 'LINK', 'DOWN', 'NUM', 'COMMA', 'ALPHA', 'COLON', 'MINUS', 'BRKT', 'DOT', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', 'UNDERSCORE', got 'DEFAULT'
```

**Expected behavior**
Should produce diagram

**It looks like word `default` breaks the flowchart, so is there any way to avoid this problem, or a list  in the documentation which includes all the words reserved?**

**Comment by xurizaemon** [comment] 2021-11-25 08:38
Can be reproduced on https://mermaid.live or gitlab.com ([example](https://gitlab.com/-/snippets/2211879)) for me.

This gives a syntax error:

```
flowchart LR
  subgraph foo
    revision_default
  end
```

But this does not:

```
flowchart LR
  subgraph foo
    revision_default1
  end
```

**Comment by Yash-Singh1** [comment] 2021-11-25 21:30
>  or a list in the documentation which includes all the words reserved?

Basically any words that could mean anything special. In your case `default` wouldn't be allowed because you can declare a default class:

```
    classDef default fill:#f9f,stroke:#333,stroke-width:4px;
```

That means `classDef` would also not be allowed.

> so is there any way to avoid this problem

Yes, the solution is to do `id[foo_default]` instead of `foo_default`. This would mean that in the diagram to reference `foo_default`, you would have to reference `id`, such as `A --> id`, but in the rendered diagram, it will show `foo_default`.

I think that `default` is a commonly used word that is only used as an argument for styling, so it should be permitted in node ids.

**Comment by xurizaemon** [comment] 2021-11-25 22:35
Thanks @Yash-Singh1 !

To clarify (since i don't recognize classDef syntax as JS), when you say "Basically any words that could mean anything special" is there an implicit "in (JS|react|node|perl)" there? Context: I'm a mermaid user but unfamiliar with it's internals.

Is https://github.com/mermaid-js/mermaid/issues/2495 a duplicate of "undocumented reserved words" here?

**Comment by Yash-Singh1** [comment] 2021-11-25 22:52
> To clarify (since i don't recognize classDef syntax as JS), when you say "Basically any words that could mean anything special" is there an implicit "in (JS|react|node|perl)" there? Context: I'm a mermaid user but unfamiliar with its internals.
>
> If we document that (eg) "currently any reserved word in JavaScript is invalid as a node id, as well as subgraph, end, flowchart ... " then that will give good guidance.

Any word that is reserved in the `mermaid` syntax for the diagram. The mermaid parser doesn't interfere with any language's parser but parses the diagram markup by itself. Copy pasting from `mermaid`'s internal parser for flowcharts it's mainly this:

```jison
"style"               return 'STYLE';
"default"             return 'DEFAULT';
"linkStyle"           return 'LINKSTYLE';
"interpolate"         return 'INTERPOLATE';
"classDef"            return 'CLASSDEF';
"class"               return 'CLASS';
"call"[\s]+             this.begin("callbackname");
"href"[\s]+["]          this.begin("href");
"click"[\s]+            this.begin("click");
"end"\b\s*            return 'end';
```

But there are more, so documenting them should be a good idea.

> If we document that (eg) "currently any reserved word in JavaScript is invalid as a node id, as well as subgraph, end, flowchart ... " then that will give good guidance.
>
> Also, might #2495 be a duplicate of "undocumented reserved words" here?

Yes, I think that we should document these reserved keywords and try to make them unreserved for node IDs where we can as done for default in #2513.

**Closed** 2021-12-11 06:19 UTC
Labels: Type: Other, Status: Approved, Graph: Flow, Area: Development
