### ISSUE TITLE
Linking to multiple nodes

### ISSUE THREAD

**Issue by notramo** [mermaid-js/mermaid#834] opened 2019-05-12 17:21 UTC
```mermaid
A --> B
A --> C
A --> D
B --> C
B --> D
B --> A
A --> E
B --> E
C --> E
D --> E
```
```mermaid
A --> B, C, D
B --> C, D, A
A, B, C, D --> E
```

**Comment by Dunning-Kruger** [comment] 2019-09-26 12:45
Hey @ThePenguin1140, are you still working on this? Anything we can help you with?

**Comment by jgreywolf** [comment] 2019-12-02 23:19
Should this be closed as duplicate of #916 ?

**Comment by Dunning-Kruger** [comment] 2019-12-03 13:26
@jgreywolf I believe they are different. One allows for one node to be linked to multiple. The other allows for multiple to be chained. `A -> B; A -> C` vs `A -> B; B -> C`

**Comment by jgreywolf** [comment] 2019-12-03 22:54
You are right. My bad

**Comment by knsv** [comment] 2019-12-15 14:28
There is a non obvious issue with the syntax here. The problem is that , is a valid character in the node id definition. This is unfortunate. The id statement should have been made strict alphaNum and life would be much easier.

As it is I am reluctant to do grammar changes that break existing diagrams out there.

I think we need to find another separator, maybe space or |

**Closed** 2020-01-02 18:13 UTC
Labels: Area: Development, Graph: Flow, Help wanted!, Status: Approved, Type: Enhancement
