### ISSUE TITLE
Basic LaTeX support

### ISSUE THREAD

**Issue by theogf** [mermaid-js/mermaid#2037] opened 2021-05-02 11:01 UTC
I just encountered mermaid via Typora and this is such an amazing tool! However coming from the scientific side I can only regret that there is no LaTeX support as mentioned in #1387.

I think mermaid would directly gain attention and interested from the whole scientific community if one was allowed to write code as:
```mermaid
graph LR;
    omega(($\omega_1$))
    sigma(($\sigma_1$))
    omega --> sigma
```

This could easily replace Tikz entirely :)

**Comment by DaveJarvis** [comment] 2022-12-14 22:05
This can probably be closed as a duplicate of #2776

**Closed** 2023-10-04 13:00 UTC
Labels: Type: Enhancement, Status: Triage
