### ISSUE TITLE
Generated SVG has static IDs which cause issues when there are two SVGs

### ISSUE THREAD

**Issue by ittayd** [mermaid-js/mermaid#3267] opened 2022-07-28 13:21 UTC
**Describe the bug**
In the attached (zipped) html, there are two SVGs generated by mermaid. Loaded in a browser they will render with arrowheads. However, if the first SVG style has 'display:none' then not only does it disappear (as expected), but also the arrow heads in the second SVG. The reason is that they are referenced as `#arrowhead` and so the browser finds them in the first SVG, which is not displayed, hence they are not displayed.

[svgs.zip](https://github.com/mermaid-js/mermaid/files/9209941/svgs.zip)

**Expected behavior**
Create unique IDs. E.g. use the id passed to render as prefix. 
(Note: there is another generic solution which is to wrap each SVG in an iframe via srcdoc. However, then styling in the outer doc can't be applied to the svg elements which for my context of static HTML files is not good)

**Screenshots**
When both are visible:
![image](https://user-images.githubusercontent.com/33328/181514898-5401790f-d2ed-4946-afaf-85fdf4c4fc93.png)

When first one is not displayed:
![image](https://user-images.githubusercontent.com/33328/181515175-e0c802b5-5dc1-4c7d-9336-582ed05b2adf.png)

**Comment by dwhelan** [comment] 2022-09-17 04:08
I am working on #1871 and the root cause was non-unique ids for the SVG markers. And the fix for it was exactly what you suggested.

**Comment by williamthome** [comment] 2022-09-27 00:46
@dwhelan Maybe it's also related to this? https://github.com/livebook-dev/livebook/issues/1440

**Comment by dwhelan** [comment] 2022-09-30 16:50
Yes @williamthome, I believe this is root cause of what you saw with https://github.com/livebook-dev/livebook/issues/1440. I do not have an ETA on getting that merged but will respond here when it is done. Is it urgent for you?

**Comment by williamthome** [comment] 2022-10-01 12:03
Ah, sure. It's ok for me. I have no urgency.

**Comment by bjarkih** [comment] 2022-10-07 12:05
This is pretty urgent for me - would love to see your fix get merged in as soon as feasible @dwhelan 🙏🏻

**Comment by sidharthv96** [comment] 2023-09-16 03:36
Fixed in https://github.com/mermaid-js/mermaid/pull/4825

**Closed by sidharthv96** 2023-09-16 03:36 UTC
Labels: Type: Bug / Error, Status: In progress, Status: Awaiting PR
