### ISSUE TITLE
fontawesome icons not counted for width of node?

### ISSUE THREAD

**Issue by katylava** [mermaid-js/mermaid#1320] opened 2020-03-26 19:48 UTC
When I use a fontawesome icon in node text, part of it gets cut off (or is very close to the edge of the node). I've been able to work around this by including a unicode space in the node text, but once #975 is fixed that won't work any more.

`cont5("fab:fa-docker fab:fa-docker fab:fa-docker<br>fab:fa-docker Containers fab:fa-docker<br>fab:fa-docker fab:fa-docker fab:fa-docker")`:
<img width="180" alt="Screen Shot 2020-03-26 at 2 43 49 PM" src="https://user-images.githubusercontent.com/10575/77689785-43a30980-6f70-11ea-8bfb-16afb9605d38.png">

`cont4("fab:fa-docker fab:fa-docker fab:fa-docker<br>#8201; fab:fa-docker Containers fab:fa-docker #8201;<br>fab:fa-docker fab:fa-docker fab:fa-docker")`:
<img width="312" alt="Screen Shot 2020-03-26 at 2 40 32 PM" src="https://user-images.githubusercontent.com/10575/77689640-03438b80-6f70-11ea-9503-c4eb376f36cc.png">

I don't know if it matters but I'm using mermaid in Vuepress following the instructions [here](https://vuepress-examples.netlify.com/demos/diagrams/).

**Comment by butterflyx** [comment] 2020-04-30 19:48
Hi @katylava , 

Nice idea for a workaround and a pitty that it doesn't work anymore. 
Anyway I would consider this issue a duplicate of https://github.com/mermaid-js/mermaid/issues/1007

**Comment by jgreywolf** [comment] 2021-02-02 00:57
closing this in favor of #1320 due to the additional information in that issue

**Closed by jgreywolf** 2021-02-02 00:57 UTC
Labels: Status: Triage, Type: Bug / Error
