### ISSUE TITLE
Mermaid 9.2.0 triggers webpack import warning

### ISSUE THREAD

**Issue by matchaxnb** [mermaid-js/mermaid#3757] opened 2022-11-04 12:53 UTC
### Description

When I import Mermaid in my Webpack project (based on [backstage](https://github.com/backstage/backstage) with plugin [techdocs-addon-mermaid](https://github.com/johanneswuerbach/backstage-plugin-techdocs-addon-mermaid), 9.2.0 triggers a warning.

```
Compiled with problems:X

WARNING in ../../node_modules/mermaid/dist/mermaid.core.mjs 27645:52-67

Critical dependency: the request of a dependency is an expression


WARNING in ../../node_modules/mermaid/dist/mermaid.core.mjs 27659:52-63

Critical dependency: the request of a dependency is an expression
```
After investigating, it seems this is due to uses of `await import(url)` and `await import(diagram)`, `url` and `diagram` being dynamic. Webpack sees that as bad.

I would recommend 

### Steps to reproduce

1. Use Mermaid 9.2.0 in a project that uses Webpack 5.7.0
2. Build in development mode
3. See the issue
or

1. Install Backstage with Yarn 3 and up-to-date packages
2. Install plug-in https://github.com/johanneswuerbach/backstage-plugin-techdocs-addon-mermaid but set MermaidJS version to 9.2.0
3. run yarn dev
4. see the error in the web UI.

### Setup

**Desktop**

- OS and Version: ArchLinux x86_64
- Browser and Version: Chrome 106
- Built with NodeJS 16, Webpack 5.7.0, Yarn 3.

**Comment by Just-Sieb** [comment] 2022-11-04 15:29
I was having the same problem with our Backstage instance and trying to add that plugin in. I resolved the issue for now by setting the resolution in the top level package.json to lock it to Mermaid v9.1.1. It seems that this change
```
{
  ...
  "resolutions": {
    "mermaid": "9.1.1"
  },
  ...
}
```
I am guessing PR #3591 broke Webpack being able to import Mermaid

**Comment by Just-Sieb** [comment] 2022-11-04 15:30
This is also probably a duplicate of #3754

**Comment by boldt** [comment] 2022-11-08 18:18
FYI: Even with [9.2.1](https://github.com/mermaid-js/mermaid/releases/tag/v9.2.1), I still see `Critical dependency: the request of a dependency is an expression`.

**Comment by sidharthv96** [comment] 2022-11-08 18:33
But the fix for that is in https://github.com/mermaid-js/mermaid/pull/3774, which hasn't been merged yet due to pnpm issue.

**Comment by boldt** [comment] 2022-11-08 23:04
Thanks, but the release notes say, that this MR ist fixed:

> fix https://github.com/mermaid-js/mermaid/issues/3757 : Remove dynamic imports for lazy load causing issues for webpack

**Comment by sidharthv96** [comment] 2022-11-09 03:39
<img width="658" alt="image" src="https://user-images.githubusercontent.com/10703445/200731838-fed077f4-3248-46fd-a2d9-856157fe44ce.png">

Must've been a mistake, Struck it off.

**Comment by sidharthv96** [comment] 2022-11-09 09:42
Can you please test `9.2.2-rc.2`

**Comment by boldt** [comment] 2022-11-09 15:39
9.2.2 works.

**Closed** 2022-11-09 15:46 UTC
Labels: Type: Bug / Error, Status: Triage
