### ISSUE TITLE
Simple CSS edit makes SVG files editable in Inkscape

### ISSUE THREAD

**Issue by rgoubet** [mermaid-js/mermaid#4290] opened 2023-04-11 10:51 UTC
It has been reported many times that SVG output is not editable in Inkscape. A part of the solution is to add this in config.json:

```json
{
    "flowchart": {
        "htmlLabels": "false"
    }
}
```

However this does not prevent fill or stroke colors to be misrepresented. By trial and error, I found that the last element in the embedded CSS stylesheet appears to be a cause of additional issues:

```css
#mermaid-1681209734368 :root{--mermaid-font-family:"trebuchet ms",verdana,arial,sans-serif;}
```

Just removing `--` fixes it all: it does not seem to affect the display in the browser, and the file loads perfectly in Inkscape and MS Office applications. I understand that the double dash defines `mermaid-font-family` as a custom CSS property, but since it's not used anywhere, it can be removed entirely as it does not appear to be properly parsed by Inkscape.

I just wanted to share this tip as well as raise this as a potential issue.

**Comment by aloisklink** [comment] 2023-04-14 00:56
> @aloisklink will https://github.com/mermaid-js/mermaid/pull/4295 fix this?

It should improve it for some themes/diagrams.

I believe for full compatibility, we'd need to:
  - Remove CSS variables like `--mermaid-font-family` (if it's not used anywhere, we should definitely remove it!)
  - Remove the other CSS vars that are not valid in SVG1.1 that I identified in PR #4295:
    https://github.com/mermaid-js/mermaid/blob/b4164b6ab59b22d41a6066b93d821783c4b4788b/packages/mermaid/src/styles.spec.ts#L39-L51
  - Maybe have some automated e2e tests that make sure our generated SVGs are SVG1.1 compliant?
  - Ideally, we'd also want to make `"htmlLabels": "false"` the default value, so that we don't have embedded HTML in our SVGs, but I guess we can always keep that opt-in so that we don't have to make a breaking change.

There might be other bugs, but if we do make all the Mermaid SVGs compliant with SVG1.1, I wouldn't be surprised if Mermaid diagrams start rendering properly in every SVG program, not just Inkscape.

---

Side-note, I'm going to close this issue in favor of https://github.com/mermaid-js/mermaid/issues/2102.

@rgoubet, it seems like the fix is pretty simple for most diagrams, so please feel free to comment on that issue! That issue has a bunch of participants, so they might be interested in the manual fix.

It might also be worth posting in https://gitlab.com/inkscape/inkscape/-/issues/3766, since that's the bug report in Inkscape about Mermaid compatibility.

**Comment by aloisklink** [comment] 2023-04-14 00:56
Duplicate of https://github.com/mermaid-js/mermaid/issues/2102

**Closed by aloisklink** 2023-04-14 00:56 UTC
Labels: Type: Bug / Error, Topic: Styling, Topic: Platform
