### ISSUE TITLE
Subgraphs for ClassDiagrams

### ISSUE THREAD

**Issue by jcurtis-cc** [mermaid-js/mermaid#3939] opened 2022-12-23 05:26 UTC
### Proposal

It's useful to be able to make sections of class diagrams visually distinct in the same manner as `subgraph` is used for flowcharts.  Applying this to class diagrams is common in other UML languages.

### Example

```
classDiagram
direction RL

%% create graph edges
AbstractExpression <--o `Client Application` : aggregates
`Client Application` --> `Context` : uses

%% create a subgraph like in a flowchart
subgraph ast ["Abstract Syntax Tree"]
TerminalExpression --|> AbstractExpression : extends
NonTerminalExpression --|> AbstractExpression : extends
NonTerminalExpression o--> AbstractExpression : aggregates
end

%% create subgraph edge to node outside subgraph
ast -->  `Context` : uses

%% create class definitions
class AbstractExpression{
    +interpret()
}
class TerminalExpression{
    +value
    +interpret()
}
class NonTerminalExpression{
    +left
    +right
    +interpret()
}
```

### Screenshots

![interpreter_concept](https://user-images.githubusercontent.com/25715542/209276476-3c48444f-f615-4f05-a004-00694499e6b4.svg)

**Comment by jgreywolf** [comment] 2023-03-17 17:52
Dupe of #3384

**Closed by jgreywolf** 2023-03-17 17:52 UTC
Labels: Type: Enhancement, Graph: Class, Status: Triage
