### ISSUE TITLE
Support actor creation/destroy in sequence diagram

### ISSUE THREAD

**Issue by rLitto** [mermaid-js/mermaid#1838] opened 2020-12-22 16:49 UTC
**Is your feature request related to a problem? Please describe.**
I have seen sequence diagrams support creating and destroying participants, but this is not supported by Mermaid. I am trying to reproduce the diagram at the end, found at [Kong-OPA-Integration](https://github.com/open-policy-agent/contrib/blob/master/kong_api_authz/doc/basic-sequence-diagram.png)

The best I can obtain is [this](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgQVtDaHJpc3RtYXNdIC0tPnxHZXQgbW9uZXl8IEIoR28gc2hvcHBpbmcpXG4gIEIgLS0-IEN7TGV0IG1lIHRoaW5rfVxuICBDIC0tPnxPbmV8IERbTGFwdG9wXVxuICBDIC0tPnxUd298IEVbaVBob25lXVxuICBDIC0tPnxUaHJlZXwgRltmYTpmYS1jYXIgQ2FyXVxuXHRcdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

**Describe the solution you'd like**
Support for `->>*` to create participant
Support for `destroy` to destroy participant

**Describe alternatives you've considered**
Using other tools? I cannot see any way of going around it, but I see it available in other sequence diagrams

**Additional context**
Diagram to reproduce:
![basic-sequence-diagram](https://user-images.githubusercontent.com/8300410/102912581-7a616e00-4475-11eb-8bac-40dc9ec14786.png)
Best effort:
![mermaid-diagram-20201222165005](https://user-images.githubusercontent.com/8300410/102912876-ddeb9b80-4475-11eb-9f5b-79eda921a979.png)

**Comment by gaelmotte** [comment] 2022-10-21 08:58
Duplicate of https://github.com/mermaid-js/mermaid/issues/1838

**Comment by michaelabuckley** [comment] 2023-03-02 23:29
PlantUML turns a message into a create message with a line before.  E.g.
```plantuml
create Persistence
Booter -> Persistence : create message
```

**Comment by Valentine14th** [comment] 2023-04-21 21:35
Hello, I'd like to work on this issue, can I be assigned to it? Thank you

**Closed** 2023-07-02 08:15 UTC
Labels: Type: Enhancement, Contributor needed, Status: Approved, Graph: Sequence
