### ISSUE TITLE
Docs: syntax highlighting makes something very hard to read

### ISSUE THREAD

**Issue by noamraph** [mermaid-js/mermaid#5007] opened 2023-11-02 14:15 UTC
### Description

See this screenshot, of https://mermaid.js.org/syntax/gitgraph.html:
![image](https://github.com/mermaid-js/mermaid/assets/1553464/2744d8fe-28b9-445e-bd89-89aa78d4d9cc)
The end of this line is nearly invisible:
```
 merge nice_feature id: "customID" tag: "customTag" type: REVERSE
```

### Steps to reproduce

Go to https://mermaid.js.org/syntax/gitgraph.html

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by noamraph** [comment] 2023-11-02 14:21
BTW, also nearly invisible here:
![image](https://github.com/mermaid-js/mermaid/assets/1553464/07642df1-bfda-4004-b1cb-c9b9d5dbb98e)

**Comment by huynhicode** [comment] 2023-11-02 14:27
@noamraph Thanks for logging this issue.

There is an open [PR](https://github.com/mermaid-js/mermaid/pull/4998) that will fix light mode code blocks.  I am going to close this issue as it is a duplicate of a previously logged one [#4971 ](https://github.com/mermaid-js/mermaid/issues/4971).

Please reach out with any questions.  Thank you!

**Closed by huynhicode** 2023-11-02 14:27 UTC
Labels: Type: Bug / Error, Status: Triage
