### ISSUE TITLE
"mainBranchName" not handled properly

### ISSUE THREAD

**Issue by AKStratus** [mermaid-js/mermaid#4430] opened 2023-05-15 09:03 UTC
**Describe the bug**
gitGraph diagrams that use "mainBranchName" do not render from the first time.

**To Reproduce**
Go to mermaid.live. Open some different diagram.

1. Go to  mermaid.live
2. Open any diagram.
3. Paste this in the editor: "%%{init:{   "logLevel":"debug",   "theme":"forest",   "gitGraph":{      "showBranches":true,      "showCommitLabel":true,      "mainBranchName":"master"   }}}%%
gitGraph
commit
branch feature/BAR_foo
checkout master"

**Expected behavior**
Diagram is displayed.
**Actual behavior**
Error is displayed. SEE COMMENTS BELOW.

**Screenshots**
![Screenshot 2023-05-13 184708](https://github.com/mermaid-js/mermaid-live-editor/assets/75667523/a6e747b4-06b5-4347-a2b5-e6632fa9e010)

**Desktop (please complete the following information):**
- OS: Win 11
- Browser chrome
- Version 10.1.0

**Additional context**
This bug occurs on live editor and also when running mermaid as js library. Note that after error is displayed if user clicks on ctrl+enter it will display diagram. Also every next time when I open live editor and this diagram is cached it will render. In js code if I call mermaid.initialize and then mermaid.render it will fail. Workaround is to call mermaid.parse before mermaid.render. For some reason "mainBranchName" is not handled properly. All diagrams without this param work as expected.

**Comment by thetimbecker** [comment] 2023-07-28 15:47
Thie problem is also mentioned here: https://github.com/mermaid-js/mermaid/issues/3191#issuecomment-1514028620

And is probably related to this one as well: https://github.com/mermaid-js/mermaid/issues/4141

I cannot find a way to use `mainBranchName` in our documentation with this bug. I am trying to find a workaround that might call mermaid.parse, but I don't think I have that control in GitHub docs.

**Comment by jgreywolf** [comment] 2023-10-04 13:16
Closing as duplicate of #4141 (copying the information there)

**Closed by jgreywolf** 2023-10-04 13:16 UTC
Labels: Status: Triage
