### ISSUE TITLE
direction in subgraph of flowchart is not taking effect

### ISSUE THREAD

**Issue by TimePrinciple** [mermaid-js/mermaid#4619] opened 2023-07-08 04:00 UTC
### Description

The `direction` specification like `TB` in a subgraph is not taking effect when one node in the subgraph is to be linked to external node.

### Steps to reproduce

```mermaid
flowchart LR
  original_file -.-> inode
  subgraph left [ ]
    direction BT
    original_file("`name_A
    *(ordinary file)*`")
    softlink_file("`name_B
    *(soft link)*`")
    softlink_file -.-> original_file 
  end
  inode("`Location
  of file
  on disk`")
```

### Screenshots

<img width="491" alt="image" src="https://github.com/mermaid-js/mermaid/assets/52569592/0668a7c7-35e3-482a-a6b1-60e7c98f3310">

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

### Additional Context

The expected output is as the screen shot described, but the dot link is from `original file` to `Location of file on disk`.

**Comment by Yokozuna59** [comment] 2023-07-08 06:41
duplicate of #2509

**Closed by Yokozuna59** 2023-07-08 06:41 UTC
Labels: Type: Bug / Error, Status: Triage
