### ISSUE TITLE
text overflow in messageline and note boxes for sequence diagrams

### ISSUE THREAD

**Issue by rajasekaran2003** [mermaid-js/mermaid#920] opened 2019-09-01 19:28 UTC
https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5wYXJ0aWNpcGFudCBBXG5wYXJ0aWNpcGFudCBCXG5BLT4-QjogbWVzc2FnZSBsaW5lIG92ZWZsb3cuIGlmIGl0cyBsb25nZXIgLCBpdCBvdmVyZmxvd3MgYW5kIGdldHMgY3V0IG9mZiB0b28gYmV5b25kIGEgY2VydGFpbiBsZW5ndGhcbk5vdGUgcmlnaHQgb2YgQTogdGV4dCBvdmVyZmxvdyBmb3Igbm90ZSBib3hlc1xuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0

text overflows for messageline and note boxes in sequence diagrams. It would be nice to have parity with how flowcharts work in this regard as they readjust the size of labels according to the length of the text.

**Comment by jgreywolf** [comment] 2020-01-14 18:03
This looks to be a duplicate of #494

**Comment by dany74q** [comment] 2020-04-23 05:07
I've tackled similar overflow issues, namely:

- When the actor description is larger than the configured actor width
- When there are notes with text that is larger than their hosting rectangle
- When there are participant messages with text that is larger than the configured actor margin

I propose fixes to the above in the following PR:
#1365

**Comment by dany74q** [comment] 2020-04-29 10:59
@knsv - I think #1365 treats this as well, feel free to close if you think so as well.

**Comment by jgreywolf** [comment] 2021-02-02 00:59
Merged with #1365

**Closed by jgreywolf** 2021-02-02 00:59 UTC
Labels: Area: Development, Graph: Sequence, Status: Approved, Type: Bug / Error
