### ISSUE TITLE
gitGraph throws error in wrong format for live editor.

### ISSUE THREAD

**Issue by gh-andre** [mermaid-js/mermaid#3191] opened 2022-05-06 18:22 UTC
**Describe the bug**

Cannot change the main branch to anything.

**To Reproduce**
Go to https://mermaid.live and select Git Graph from the samples pane.

Change config to this:
```json
{
  "theme": "default",
  "gitGraph": {
    "mainBranchName": "trunk"
  }
}
```
Go back to the diagram and try to change `main` to `trunk`. It blinks and won't change anything. The console lights up with errors like this:
```
Uncaught Error: D.hash.loc is undefined

S@https://mermaid.live/_app/pages/edit.svelte-6f83f87b.js:109:13610
ln/</<@https://mermaid.live/_app/chunks/index-3ccfa173.js:4:906
ln/<@https://mermaid.live/_app/chunks/index-3ccfa173.js:4:892
In/</</<@https://mermaid.live/_app/pages/edit.svelte-6f83f87b.js:14:1891
```
Trying it the other way around - changing `main` to `trunk` in the editor first (before config), logs that a branch isn't created yet, as expected, then changing `main` in config to `trunk` resets the editor back to `main`.

**Expected behavior**

The editor shall allow users to change the name of the main branch to an arbitrary name.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: FireFox, Chrome
- Version: both latest, as of this post

**Comment by knsv** [comment] 2022-08-21 09:25
@ashishjain0512 Can we close this now? Perhaps we should add the std info in the custom errors thrown.

**Comment by ashishjain0512** [comment] 2022-08-23 16:20
This issue is now fixed. Verified in Mermaid Live Editor against mermaid v9.1.6

**Closed by ashishjain0512** 2022-08-23 16:20 UTC
Labels: Type: Bug / Error, Graph: Git, bug

**Comment by marpants** [comment] 2023-04-19 02:00
So, this does not seem to be fully resolved..
Video attached shows that when copying into the live editor it initially throws the error until the trailing line is removed.
https://user-images.githubusercontent.com/61366665/232946289-41a5c7b8-916d-49d2-9ba7-b2d1e6de06e7.mp4
- I did test copy pasting other snippets in the same way as the above video and they didn't have the same problem.

The issue is present (and I can't find a resolution) in 'Markdown Preview Mermaid Support' v1.18.1 VS code using Mermaid 10.1.0
![image](https://user-images.githubusercontent.com/61366665/232947035-f3ae3042-5470-4be9-a2bf-3173361a53d3.png)
Without using the 'mainBranchName' behavior is normal.
This is the issue I actually care about
