### ISSUE TITLE
StateDiagram v 9.1.0 render error ?

### ISSUE THREAD

**Issue by megaadam** [mermaid-js/mermaid#3048] opened 2022-05-17 14:42 UTC
I use Mermaid via the Yzane vs code plugin, and it uses the Mermaid server at https://unpkg.com/mermaid@9.1.1/dist/mermaid.min.js
(Redirected via https://unpkg.com/mermaid/dist/mermaid.min.js)

The **code below** renders into broken PDF with version `9.1.1` and `9.1.0` however if I change the render URL version to `9.0.0` then the output is fine. 

**I dunno whether the Mermaid code is broken or if something has gone wrong at unpkg.com.** Not sure how to contact unpkg. I hope that you can resolve this  (or find the "culprit")  for the benefit of others. Anyway, I thank the Mermaid community for your awesome work.

    ```mermaid
    stateDiagram
        direction LR
        File --> Vod2Cbm
        http   --> Vod2Cbm
        S3   --> Vod2Cbm
        Vod2Cbm --> Repackager: ESF
        Note right of Vod2Cbm: Schedule
        TC: Test Client
        Vod2Cbm --> TC
        Repackager --> Client
    
    ```

**Comment by ashishjain0512** [comment] 2022-05-17 15:18
@megaadam  This given example is for **_stateDiagram_** and it works in 9.1.1. 
Could you share a sample for **sequenceDiagram** where you faced the challenge? 
Also, try in https://mermaid.live with your code snippet as it uses the latest version as well. Will help narrow down if it is the plugin or not.

See the diagram attached for your reference: 

![image](https://user-images.githubusercontent.com/16836093/168846594-9499f89e-2349-4b7a-8b02-5ace9156861c.png)

**Comment by megaadam** [comment] 2022-05-19 11:38
@ashishjain0512  sorry, see above

**Comment by knsv** [comment] 2022-08-20 12:21
Hi @megaadam!

I am going through old issues and wonder if this one still is a problem. I can not reproduce the issue in the live editor or in a html page. If it still is a problem, please advice on how to reproduce it.

Thanks,
Knut

**Comment by nirname** [comment] 2023-07-11 16:11
@megaadam this issue is here for quite a while, and I cannot reproduce it neither in editor nor in the latest version, so I am closing this; perhaps it is related to plugin. Please, ask to reopen it is still actual

**Comment by Yokozuna59** [comment] 2023-07-11 17:12
@nirname I guess the convention we are following is to add `Close after 30 days` labels, and after that period, we close the issue. Although some issues have this label and are still not closed after this period :)

**Comment by nirname** [comment] 2023-07-11 17:14
@Yokozuna59 thanks for the catch, I've noticed that a bit too late, I think we will try to follow that procedure. I am reopening the issue and marking at for the closing

**Closed** 2023-09-15 08:50 UTC
Labels: Type: Bug / Error, Status: Triage, Close after 30 days
