### ISSUE TITLE
Error when creating flowcharts

### ISSUE THREAD

**Issue by nadachra** [mermaid-js/mermaid#3174] opened 2022-06-23 16:39 UTC
**Describe the bug**
When creating a flowchart I am met with an error.
Currently I'm unable to create any flowcharts. I'm using version 9.1.2.
The error is a parsing error. 

I only encounter this issue when creating flowcharts, other charts seem to be working.

**To Reproduce**
Create a flowchart:
flowchart TD
    A[Start] --> B{Is it?}
    B -- Yes --> C[OK]
    C --> D[Rethink]
    D --> B
    B -- No ----> E[End]

**Expected behavior**
Flowchart should be created.

**Screenshots**
![error](https://user-images.githubusercontent.com/70055041/175349735-23fe4585-921f-44f2-9f1a-78417883fa56.png)

**Code Sample**
If applicable, add the code sample or a link to the [live editor](https://mermaid-js.github.io/mermaid-live-editor).

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Comment by sidharthv96** [comment] 2022-06-28 19:32
@nadachra, the flowchart you shared is rendered properly in live editor.
https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNo9kE1vgzAMhv9K5HNbVthoy2HTWjhMkzZp3aUiHFLiQDRIEDibKsR_X-g-Lpb9-H1t2SOUViIkoBr7VdaiJ_aecvOYH8nnBVsu79l-fBqYpoeJm70H7ITDlR_y1-eCm8O1SPM3pFqbD0_SH9uv_MX6OIMsz4wsYAEt9q3Q0m8duWGMA9XYIofEpxKVcA1x4GbyUtdJQZhJTbaHRIlmwAUIR_Z4MSUk1Dv8E6VaVL1o_1WNFRK9aQS6dPOJlR7IjyytUbqauesbj2uibkiCYG6vKk21O69K2waDlvM_6s9dHMRhvBVhhPEmEndRJMvzerdV4e1ayc3NOhQwTdM3xyBpwg

**Comment by knsv** [comment] 2022-08-14 14:46
Closing this issue as we cant reproduce it!

**Closed by knsv** 2022-08-14 14:46 UTC
Labels: Type: Bug / Error, Awaiting Reply, Close after 30 days
