### ISSUE TITLE
A certain simple graph does not render; gives error

### ISSUE THREAD

**Issue by rpus** [mermaid-js/mermaid#4201] opened 2023-03-08 07:48 UTC
### Description

Hi... This:

```mermaid
graph TD
  a-->b11
  subgraph b1
    subgraph b11
      subgraph b111
      end
    end
  end
  b1-->c
```

gives:

`Cannot read properties of undefined (reading 'id')`

(even in mermaid 9.4.0).

### Steps to reproduce

Repro as above!

### Code Sample

```text
// as above!
```

### Setup

- Mermaid version: 9.4.0
- Browser and Version: [Chrome, Edge, Firefox]

### Additional Context

Numerous other/similar case are fine btw (so these will be good to check as tests):

```mermaid
graph TD
  a-->b11
  subgraph b1
    subgraph b11
    end
  end
  b1-->c
```

```mermaid
graph TD
  a-->b11
  subgraph b1
    subgraph b11
      subgraph b111
      end
    end
  end
```

```mermaid
graph TD
  subgraph b1
    subgraph b11
      subgraph b111
      end
    end
  end
  b1-->c
```

```mermaid
graph TD
  a-->b11
  subgraph b1
    subgraph b11
    end
    subgraph b12
    end
  end
  b1-->c
```

**Comment by ioggstream** [comment] 2023-07-11 13:15
Same error for the following (simpler) graphs

```
graph TD

a-->b1

subgraph b1
b11
end

subgraph b11
b111
end

b11-->c

```

### Trace

```
View.669324eb.js:3 view fail TypeError: Cannot read properties of undefined (reading 'id')
    at index-1e7f2254.c8c71bd0.js:1:10249
    at Array.map (<anonymous>)
    at $ (index-1e7f2254.c8c71bd0.js:1:9522)
    at index-1e7f2254.c8c71bd0.js:1:9912
    at Array.map (<anonymous>)
    at $ (index-1e7f2254.c8c71bd0.js:1:9522)
    at gt (index-1e7f2254.c8c71bd0.js:1:11488)
    at Object.le [as draw] (styles-7882abfe.1296b518.js:2:1390)
    at Object.render$1 [as render] (state.f87e7922.js:87:1021)
```

**Comment by nirname** [comment] 2023-07-11 15:44
This is a duplicate of #4508

**Comment by nirname** [comment] 2023-07-11 15:46
https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/dagre-wrapper/index.js#L72

**Comment by nirname** [comment] 2023-07-16 13:20
Closing in favor of #4644

**Closed by nirname** 2023-07-16 13:20 UTC
Labels: Type: Bug / Error, Contributor needed, Status: Approved, Area: Development, Internals: Renderer
