### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createElementNS')

### ISSUE THREAD

**Issue by Thoybur-Rohman** [mermaid-js/mermaid#4484] opened 2023-06-12 12:18 UTC
### Description

**Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createElementNS')** 

When I try to render the code Please see below my Blazor.cs file and script 

### Steps to reproduce

1 : Make a cs file : 
@inject IJSRuntime JSRuntime

<div>
    <label for="input">Input:</label>
    <textarea id="input" @bind="@InputText" @oninput="RenderDiagram"></textarea>
</div>
<div>
    <label for="output">Output:</label>
    <div id="output">@OutputText</div>
</div>

@code {
    private string InputText = "";

    private string OutputText = "";

    private async Task RenderDiagram()
    {
        await JSRuntime.InvokeVoidAsync("renderMermaidDiagram");
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await JSRuntime.InvokeVoidAsync("mermaid.initialize", new { startOnLoad = true });
            await JSRuntime.InvokeVoidAsync("renderMermaidDiagram");
        }
    }
}

Step 2 :  <script>
        window.renderMermaidDiagram = () => {
        var output = document.getElementById("output");
        var input = document.getElementById("input").value;

        if (input != "") {
            try {
                mermaid.mermaidAPI.parse(input); // Syntax validation
                mermaid.mermaidAPI.render('theGraph', input, function (svgCode) {
                    output.innerHTML = svgCode;
                });
            } catch (error) {
                output.innerHTML = "Invalid syntax"; // Display error message
            }
        }
    }

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/73062879/53b02e76-f9c3-4fd2-9986-c560aa800804)

### Code Sample

```text
Blazor.cs File :

@page "/
@inject IJSRuntime JSRuntime

<div>
    <label for="input">Input:</label>
    <textarea id="input" @bind="@InputText" @oninput="RenderDiagram"></textarea>
</div>
<div>
    <label for="output">Output:</label>
    <div id="output">@OutputText</div>
</div>

@code {
    private string InputText = "";

    private string OutputText = "";

    private async Task RenderDiagram()
    {
        await JSRuntime.InvokeVoidAsync("renderMermaidDiagram");
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await JSRuntime.InvokeVoidAsync("mermaid.initialize", new { startOnLoad = true });
            await JSRuntime.InvokeVoidAsync("renderMermaidDiagram");
        }
    }
}

Script : 
  <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>

  <script>
        window.renderMermaidDiagram = () => {
        var output = document.getElementById("output");
        var input = document.getElementById("input").value;

        if (input != "") {
            try {
                mermaid.mermaidAPI.parse(input); // Syntax validation
                mermaid.mermaidAPI.render('theGraph', input, function (svgCode) {
                    output.innerHTML = svgCode;
                });
            } catch (error) {
                output.innerHTML = "Invalid syntax"; // Display error message
            }
        }
    }
```

### Setup

- Mermaid version: Not sure 
- Browser and Version: [Chrome, Edge,]

### Additional Context

Please see my files i added

**Comment by sidharthv96** [comment] 2023-06-12 18:29
Render function signature has changed in v10 as a breaking change.
Duplicate of https://github.com/mermaid-js/mermaid/issues/4442

Also, don't use `mermaid.mermaidAPI.render`. Use `mermaid.render` instead.

**Closed by sidharthv96** 2023-06-12 18:29 UTC
Labels: Type: Bug / Error, Status: Triage
