### ISSUE TITLE
using mermaid.js from node.js without headless web browser?

### ISSUE THREAD

**Issue by ds2345** [mermaid-js/mermaid#3886] opened 2022-12-03 15:16 UTC
### Proposal

is there a way to render mermaid.js diagrams to svg from node.js (server) app
without starting "headless" web browser via mermaid cli as it was suggested in some comments?

if not, what would be required to add or change in the system to enable such rendering?

thank you

**Comment by aloisklink** [comment] 2022-12-07 22:46
It's not currently possible unfortunately, since Mermaid relies on the browser's layout engine to correctly size/place items. As far as I'm aware, this isn't possible with `jsdom` (what most people use for server-side rendering).

It might be possible with the `svgdom` library, though, but nobody has yet tried it out.

Contributions are welcome though (although please add any comments to issue https://github.com/mermaid-js/mermaid/issues/3650)!

This is a pretty heavily requested feature, so it would be amazing if we could get proper server-side rendering working.

Duplicate of https://github.com/mermaid-js/mermaid/issues/3650

**Comment by aloisklink** [comment] 2022-12-07 22:46
Duplicate of https://github.com/mermaid-js/mermaid/issues/3650

**Closed by aloisklink** 2022-12-07 22:46 UTC
Labels: Type: Enhancement, Status: Triage
