### ISSUE TITLE
Unnecessary crossing of arcs

### ISSUE THREAD

**Issue by wouterbeek** [mermaid-js/mermaid#2053] opened 2021-05-08 17:27 UTC
**Describe the bug**

An important property of readable graphs is that they do not have too many arc intersections.  While it is not always possible to avoid arc intersections, sometimes they are necessary to depict the user's graph specification into a 2D place, superfluous arc intersections should be avoided as much as possible.

**To Reproduce**

Open this example diagram in the live editor: [link](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG4gIFBsYWNlIDx8LS0gQWRtaW5pc3RyYXRpdmVBcmVhXG4gIFN0cnVjdHVyZWRWYWx1ZSA8fC0tIEdlb0Nvb3JkaW5hdGVzXG4gIEFkbWluaXN0cmF0aXZlQXJlYSAtLT4gQ291bnRyeSA6IGNvbnRhaW5lZEluUGxhY2VcbiAgU3RydWN0dXJlZFZhbHVlIDx8LS0gQ29udGFjdFBvaW50XG4gIEFkbWluaXN0cmF0aXZlQXJlYSAtLT4gUGxhY2UgOiBjb250YWluc1BsYWNlXG4gIFBsYWNlIDx8LS0gQ2l2aWNTdHJ1Y3R1cmUiLCJtZXJtYWlkIjp7fSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

Or generate the class diagram for the following Mermaid snippet:

```
classDiagram
  Place <|-- AdministrativeArea
  StructuredValue <|-- GeoCoordinates
  AdministrativeArea --> Country : containedInPlace
  StructuredValue <|-- ContactPoint
  AdministrativeArea --> Place : containsPlace
  Place <|-- CivicStructure
```

Or look at the screenshot included below.

Notice that the crossing arc is introduced unnecessarily.  It makes the graph more difficult to process for a human user.

Also notice that the crossing arc appears somewhat arbitrarily: moving the non-first lines in the above text snippet around sometimes results in 0 crossing arcs and sometimes results in 1 crossing arc in a different place.

**Expected behavior**

I expect to see unnecessarily crossing arcs in much fewer cases.

**Screenshots**

![Screenshot from 2021-05-08 19-13-21](https://user-images.githubusercontent.com/1685012/117547734-810e0d80-b031-11eb-9ce8-3ab584be4286.png)

**Code Sample**

See the reproducibility steps above.

**Desktop (please complete the following information):**

 - OS: Linux/Ubuntu
 - Browser: Chrome
 - Version: 8.9.0

**Comment by jgreywolf** [comment] 2024-08-27 14:24
Closing as a duplicate of #1305

**Closed by jgreywolf** 2024-08-27 14:24 UTC
Labels: Type: Bug / Error, Graph: Class, Status: Triage, Internals: Renderer
