### ISSUE TITLE
Callback for state diagrams

### ISSUE THREAD

**Issue by ramstein74** [mermaid-js/mermaid#1100] opened 2019-11-28 12:49 UTC
Hello i noticed that i can use callbacks/interaction in flowcharts but not in state diagrams.
Is that so ?
Regards

**Comment by jgreywolf** [comment] 2021-02-25 22:51
@ramstein74 Yes, callbacks are currently not supported in state diagrams.  Are you interested in taking this issue on? :)

**Comment by jgreywolf** [comment] 2023-03-07 15:54
Closing as duplicate of #1139

**Closed by jgreywolf** 2023-03-07 15:54 UTC
Labels: Type: Enhancement, Area: Development, Graph: State, Status: Awaiting Reply
