### ISSUE TITLE
Line instead of arrow towards hexagon shape in subgraph

### ISSUE THREAD

**Issue by f-skold** [mermaid-js/mermaid#1667] opened 2020-09-08 21:57 UTC
**Describe the bug**
I see a line instead of an arrow as I epxpect, when drawing a flowchart in a subgraph.

**To Reproduce**

Let mermaid draw the code below. Here when I am using hexagon shape "{{ }}" for d14, no arrow tip is seen.

```mermaid
flowchart LR
  subgraph deploy_flow[Deploy version to production]
     
     d11([check version exists]) --> d12([check status green of environment])
     d12 --> d13([check if version already running])
     d13 --> d14{{d14: deploy to production}}
  end

  commit([Change in meta/gitops]) --> shared[(shared repo)]
  shared ==>|triggers| deploy_flow
```

Changing the shape of d14 to rectangular "[ ]" makes the arrow tip appear.

```mermaid
flowchart LR
  subgraph deploy_flow[Deploy version to production]
     
     d11([check version exists]) --> d12([check status green of environment])
     d12 --> d13([check if version already running])
     d13 --> d14[d14: deploy to production]
  end

  commit([Change in meta/gitops]) --> shared[(shared repo)]
  shared ==>|triggers| deploy_flow
```

**Expected behavior**
I expect the arrow to work for the hexagon shape.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Browser firefox
 - Version 80.0.1 (64-bit)

**Comment by GDFaber** [comment] 2021-01-24 20:01
Hi @f-skold, thanks for your report. I'm closing this issue in favour of #1620 where the problem is also addressed.

**Closed by GDFaber** 2021-01-24 20:01 UTC
Labels: Status: Triage, Type: Bug / Error
