### ISSUE TITLE
Sequence diagram | big blank space above and under diagram when number of actors increasing

### ISSUE THREAD

**Issue by pawskipawel** [mermaid-js/mermaid#1928] opened 2021-03-05 08:03 UTC
When I use sequence diagram with for example 8 actors, there is a big blank space above and under diagram. It is a problem when using diagram on readme in Markdown format. 

Similar issue: https://discourse.joplinapp.org/t/excessive-whitespace-around-sequence-diagrams/12355/9

![image](https://user-images.githubusercontent.com/12270978/110085842-e293d080-7d91-11eb-89a1-f7431446f909.png)

![image](https://user-images.githubusercontent.com/12270978/110085764-cabc4c80-7d91-11eb-9c61-f8fb9e54eeb2.png)

**Comment by sradforth** [comment] 2021-04-08 08:50
I'm having this same issue and effects viewing in gitlab, vscode and exporting to PDF.  I've not noticed it before but seems to happen on all sequence diagrams now.
The gap gets bigger for each participant in the sequence.

It appears to be due to the SVG element height being set to perhaps the width value.  Exporting to HTML and editing it I can adjust the SVG height attribute to the correct value to fix this.

![Screenshot from 2021-04-08 09-49-02](https://user-images.githubusercontent.com/4855227/113997115-bd422880-984f-11eb-98f9-3d9753765577.png)

**Comment by sradforth** [comment] 2021-04-08 12:03
Looking at it a bit more, perhaps `<svg  ... height= ` should be `<svg  ...max-height=` as that would solve the problem.

**Comment by sidharthv96** [comment] 2023-02-20 04:29
Please have a look at the newly introduced Timeline Diagram: https://mermaid.js.org/syntax/timeline.html

---
_This issue was closed by a human, not a bot. Please re-open if necessary._

**Comment by jgreywolf** [comment] 2023-04-05 16:14
Closing as a duplicate of #1929

**Closed by jgreywolf** 2023-04-05 16:14 UTC
Labels: Type: Bug / Error, Contributor needed, Status: Approved, Graph: Sequence
