### ISSUE TITLE
Huge Gap Is showing before and after the rendered of sequence diagram

### ISSUE THREAD

**Issue by MayurMundekar** [mermaid-js/mermaid#2481] opened 2021-11-12 08:08 UTC
**Describe the bug**
We are migrating from 8.2.6 to 8.12.0 one of our existing diagram is not rendering properly in 8.12.0. In mermaid 8.2.6 one of our sequence diagram is rendering properly but in 8.12.0 there is huge gap before and after the sequence diagram. We verified in mermaid live editor and there also it is giving same issue.

**Expected behavior**
There should not be gap before and after the sequence diagram

**Screenshots**
**1.Sequence Diagram rendered using 8.2.6**
<img width="847" alt="2021-11-12 13_34_32-Sequence Diagram breaking issue - Overview" src="https://user-images.githubusercontent.com/83640993/141432538-12a81d61-798b-46fc-917d-035e1f358422.png">

**Sequence Diagram rendered using 8.12.0**
<img width="850" alt="2021-11-12 13_35_17-Gap in sequence diagram - Overview" src="https://user-images.githubusercontent.com/83640993/141432704-fa154038-b7b3-4d3f-9681-8ffb9561ff62.png">

**Code Sample**
sequenceDiagram
 participant Alice
 participant Bob

 participant ABC
 participant XYZ

 participant UVW
 participant MAN

 participant DUDE

par [Action to Bb]
Alice->>+Bob: Hello Bob, how are you?
Bob->>-Alice: Hello Alice, how are you?
 Note Right of Bob: Delete Old Imports
 Note Right of Bob: Picks SPS Instance
and [Action to AA]
ABC->>+XYZ: Hello XYZ, how are you?
XYZ->>-ABC: Hello ABC, how are you?
and [Action to AA]
ABC->>+XYZ: Hello XYZ, how are you?
XYZ->>-ABC: Hello ABC, how are you?
and [Action to AA]
ABC->>+XYZ: Hello XYZ, how are you?
XYZ->>-ABC: Hello ABC, how are you?
and [Action to AA]
ABC->>+XYZ: Hello XYZ, how are you?
XYZ->>-ABC: Hello ABC, how are you?
and [Action to AA]
ABC->>XYZ: Hello XYZ, how are you?
XYZ->>ABC: Hello ABC, how are you?
and [Action to AA]
ABC->>XYZ: Hello XYZ, how are you?
XYZ->>ABC: Hello ABC, how are you?
and [Action to AA]
ABC->>XYZ: Hello XYZ, how are you?
XYZ->>ABC: Hello ABC, how are you?
and [Action to AA]
ABC->>XYZ: Hello XYZ, how are you?
XYZ->>ABC: Hello ABC, how are you?

end

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 95.0

**Comment by MayurMundekar** [comment] 2021-11-15 05:13
Hi Team, Any update on this ?

**Comment by Luxizzle** [comment] 2021-11-29 10:41
Also seeing this issue in my sequence diagrams

**Comment by Yokozuna59** [comment] 2023-08-09 22:45
duplicate of #1929

**Closed by Yokozuna59** 2023-08-09 22:45 UTC
Labels: Type: Bug / Error, Graph: Sequence, Status: Triage, Internals: Renderer
