### ISSUE TITLE
Is there a way to prevent lines from going under nodes?

### ISSUE THREAD

**Issue by rlopezro** [mermaid-js/mermaid#1117] opened 2019-12-04 23:59 UTC
Hi all! In large diagrams I see lines going under nodes. Is there a configuration option that will force lines to never go under nodes? Here is a screenshot.

<img width="235" alt="Screen Shot 2019-12-04 at 3 52 34 PM" src="https://user-images.githubusercontent.com/15841313/70191822-dca2d180-16ae-11ea-946d-b45fc05c78aa.png">

Thanks!

**Comment by Dunning-Kruger** [comment] 2019-12-05 00:06
@rlopezro Hello! It seems this is, basically, a duplicate of #1006! Sadly, it appears there's no solution to the problem for large diagrams, for now. Feel free to follow up on it on #1006

**Closed by Dunning-Kruger** 2019-12-05 00:06 UTC
Labels: Help wanted!, Status: Triage, Type: Other
