### ISSUE TITLE
subclassDiagram

### ISSUE THREAD

**Issue by carterbox** [mermaid-js/mermaid#1180] opened 2020-01-06 18:28 UTC
I would like to be able to use the [`subgraph`](https://mermaid-js.github.io/mermaid/#/flowchart?id=subgraphs) feature from Flowchart in [`classDiagrams`.](https://mermaid-js.github.io/mermaid/#/classDiagram) This is because it would allow me to show in my class diagram how groups of classes are organized into modules or packages.

**Comment by chris579** [comment] 2020-01-06 19:26
Duplicate of #1052

**Closed by chris579** 2020-01-06 19:26 UTC
Labels: Status: Triage, Type: Enhancement
