### ISSUE TITLE
Entity Relationship Diagram documentation bug

### ISSUE THREAD

**Issue by ChloeLiang** [mermaid-js/mermaid#2653] opened 2022-01-21 15:39 UTC
**Describe the bug**

1. The document says using double quotes for comment. I think it's not true.
2. The diagram UI is not rendered correctly.

**To Reproduce**
1. Go to https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram?id=attribute-keys-and-comments
2. It says `And a comment is defined by double quotes at the end of an attribute.`. I expect the comment not to render, but it is.
3. See the diagram.

**Expected behavior**
1. Comment is not rendered.
2. Diagram is displayed correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/28077042/150554627-1c103cf5-764b-4c71-ba5d-9ccd9eac0fd1.png)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by Arakade** [comment] 2022-01-24 10:14
Is this a duplicate of https://github.com/mermaid-js/mermaid/issues/2548 
I came here to report ~~the same~~ a _similar_ thing.  I took "comment" as "annotation" or "comment for the reader of the diagram".  I think that's why it's rendered.  I completely agree it's rendered incorrectly though!

**Comment by ChloeLiang** [comment] 2022-01-26 13:05
Hi @Arakade , you're right. It seems like a duplicate issue. I'll close this one. Thanks!

**Closed** 2022-01-26 13:06 UTC
Labels: Type: Bug / Error, Status: Triage
