### ISSUE TITLE
Declare necessary deps

### ISSUE THREAD

**Issue by Mister-Hope** [mermaid-js/mermaid#2962] opened 2022-04-24 16:08 UTC
I am curious, why should every usr install packages like "cypress-image-snapshot" "cypress" "jest"?

Shouldn't they moved to devDependencies?😑

**Comment by mmorel-35** [comment] 2022-04-25 20:07
Hi @Mister-Hope,

Where have you seen that they aren't?
https://github.com/mermaid-js/mermaid/blob/170ed89e9ef3e33dc84f8656eed1725379d505df/package.json#L70-L95

**Comment by sgerace** [comment] 2022-04-26 15:27
I happened to stumble on this while attempting to figure out why cypress was being installed in my project which did not include it in its dependencies. I have a feeling the "ask" from @Mister-Hope is the same as mine: it would be nice if developers didn't have to install cypress just because our project includes mermaid (since in that use case, cypress will not be used because we aren't doing development on cypress, we're simply using it).

I'm honestly a little confused why this is happening in the first place, my expectation is that nested devDependencies would not be installed by default, as indicated here: https://stackoverflow.com/questions/54156483/are-node-devdependencies-included-as-part-of-a-release-if-they-are-nested-within

@mmorel-35 , I'm wondering if you are able to reproduce what we're seeing, if I use the following package.json, and run `npm install`, cypress is indeed installed:
```json
{
  "dependencies": {
    "mermaid": "9.0.0"
  }
}
```
Do you see the same behavior?

**Comment by NiamorEllievel** [comment] 2022-04-27 00:18
Hi @mmorel-35 

The branch you're checking is 170ed89e9ef3e33dc84f8656eed1725379d505df.
The "cypress-image-snapshot": "^4.0.1" dependency is present on master and release/9.0.1
You can check the list of dependencies for the release on npmjs's website too.
Moreover, without the latest cypress version explicitly installed, this installs a very old version which breaks Typescript compilation, so I'd say this should be pretty high priority.

**Comment by Yash-Singh1** [comment] 2022-04-27 16:19
This is fixed in the current state of the repository. @knsv Could you create a new release?

**Comment by Mister-Hope** [comment] 2022-05-04 18:34
Any update?

**Closed** 2022-05-11 18:52 UTC
Labels: Type: Bug / Error, Status: Triage
