### ISSUE TITLE
Upgrade "documentation" to the last version

### ISSUE THREAD

**Issue by knsv** [mermaid-js/mermaid#3351] opened 2022-08-23 17:23 UTC
A simple version change from version 13.2 to 14 is not possible without modifications. We get the following error message in the console when running the command `yarn post build`:
```
$ documentation build src/mermaidAPI.js src/config.js src/defaultConfig.js --shallow -f md --markdown-toc false > docs/Setup.md
Error: Cannot handle unknown node `table`
    at Object.unknown (file:///Users/knuts/source/priv/atlantica/mermaid/node_modules/mdast-util-to-markdown/lib/index.js:91:9)
    at Object.one [as handle] (file:///Users/knuts/source/priv/atlantica/mermaid/node_modules/zwitch/index.js:52:17)
    at containerFlow (file:///Users/knuts/source/priv/atlantica/mermaid/node_modules/mdast-util-to-markdown/lib/util/container-flow.js:34:17)
    at Object.root (file:///Users/knuts/source/priv/atlantica/mermaid/node_modules/mdast-util-to-markdown/lib/handle/root.js:13:10)
    at Object.one [as handle] (file:///Users/knuts/source/priv/atlantica/mermaid/node_modules/zwitch/index.js:52:17)
    at toMarkdown (file:///Users/knuts/source/priv/atlantica/mermaid/node_modules/mdast-util-to-markdown/lib/index.js:50:24)
    at compiler (file:///Users/knuts/source/priv/atlantica/mermaid/node_modules/remark-stringify/lib/index.js:16:12)
    at Function.stringify (file:///Users/knuts/source/priv/atlantica/mermaid/node_modules/unified/lib/index.js:290:12)
    at file:///Users/knuts/source/priv/atlantica/mermaid/node_modules/documentation/src/output/markdown.js:28:59
error Command failed with exit code 1.
```

**Help with upgrading the tool would be much appreciated!**

**Comment by aloisklink** [comment] 2022-08-26 14:27
This is due to a bug/regression in v13.2.2 and later of the the `documentation` package, which broke outputting GitHub Flavored Markdown (tables are a GFM only feature).

I've made a PR to fix it: https://github.com/documentationjs/documentation/pull/1553

**Comment by emersonbottero** [comment] 2022-10-01 04:26
My new documentation does not rely on documentation..
actually I had to remove since it conflicts with my version

**Comment by aloisklink** [comment] 2022-10-01 17:04
> My new documentation does not rely on documentation.. actually I had to remove since it conflicts with my version

Awesome :) I've updated your PR to say `Resolves https://github.com/mermaid-js/mermaid/issues/3351`, so this issue will get auto-closed if/when your PR gets merged.

To be honest, `documentation.js` is quite unmaintained right now, so it does make sense to move to a different system.

**Closed** 2022-10-04 06:24 UTC
Labels: Type: Enhancement, Contributor needed, Status: Approved, dependencies, Status: Awaiting PR
