### ISSUE TITLE
How to annotate the relation from a class member to another class or another class member

### ISSUE THREAD

**Issue by AmrIKhudair** [mermaid-js/mermaid#2341] opened 2021-09-22 07:17 UTC
I would like to make an arrow from a class member to another class or one of its members, this feature exists in PlantUML by using `::` operator for example `Class1::member1 --> Class2::member2`. I tried to use this operator in Mermaid but it gave me a syntax error. Please help!

**Comment by mebibou** [comment] 2023-01-18 13:16
Any idea when this would be implemented? classes are always linked together via member, so its a bit odd this is no supported (makes the whole Class diagram a bit pointless imo)

**Comment by Yokozuna59** [comment] 2023-08-09 21:47
duplicate of #2341

**Closed by Yokozuna59** 2023-08-09 21:47 UTC
Labels: Type: Other, Status: Triage
