### ISSUE TITLE
How to render an image in .html page?

### ISSUE THREAD

**Issue by waterdrop01** [mermaid-js/mermaid#1135] opened 2019-12-10 18:53 UTC
Hello,

I'm trying to do the same as on the Mermaid online editor, but in my own .html page.

here is the code:
```html
<html>
  <body>
    <meta charset="utf-8" />
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script>
      mermaid.initialize({ startOnLoad: true, securityLevel: "loose" });
    </script>
    <div class="mermaid">
      graph TD DIR("<img
        src="https://iconscout.com/ms-icon-310x310.png"
        ;
        width="30"
      />")
    </div>
  </body>
</html>
```
It's working on [Mermaid online editor here](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgRElSKFwiPGltZyBzcmM9J2h0dHBzOi8vaWNvbnNjb3V0LmNvbS9tcy1pY29uLTMxMHgzMTAucG5nJzsgd2lkdGg9JzMwJyAvPlwiKSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0Iiwic2VjdXJpdHlMZXZlbCI6Imxvb3NlIn19), but in my local .html page I get this error:
![Screenshot from 2019-12-10 19-50-50](https://user-images.githubusercontent.com/47316824/70559112-64dd1700-1b86-11ea-91c3-5919a9529d5f.png)

Any idea? Thanks a lot

edit: added ```securityLevel: "loose"``` with no success

**Comment by Dunning-Kruger** [comment] 2019-12-10 19:02
In your html, you're using this markup:
```
graph TD DIR("<img
  src="https://iconscout.com/ms-icon-310x310.png"
  ;
  width="30"
```

In your editor sample, you're using the following:
```
graph TD
  DIR("<img src='https://iconscout.com/ms-icon-310x310.png'; width='30' />")
```

They are not the same.

**Comment by waterdrop01** [comment] 2019-12-10 20:01
Well you are right, my editor auto formatted the code. Here is now copy paste from gedit:

```html
<html>
  <body>
    <meta charset="utf-8" />
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script>
      mermaid.initialize({ startOnLoad: true, securityLevel: "loose" });
    </script>
    <div class="mermaid">
      graph TD
        DIR("<img src='https://iconscout.com/ms-icon-310x310.png'; width='30' />")
    </div>
  </body>
</html>
```
still not working though :(
![Screenshot from 2019-12-10 20-59-37](https://user-images.githubusercontent.com/47316824/70564204-0321aa80-1b90-11ea-971b-7cbf9180b33c.png)

Thanks a lot for your help

**Comment by GDFaber** [comment] 2019-12-10 20:32
Leave out the semicolon before the 'width' attribute in your img tag and try again. Does it solve the problem?

**Comment by waterdrop01** [comment] 2019-12-10 23:58
no, I tried without the semicolon, still the following error:
```
Error: Parse error on line 2:
...ms-icon-310x310.png" width="30">")
-----------------------^
Expecting 'SEMI', 'NEWLINE', 'SPACE', 'EOF', 'GRAPH', 'DIR', 'subgraph', 'SQS', 'SQE', 'end', 'PE', '-)', 'DIAMOND_STOP', 'TAGEND', 'TRAPEND', 'INVTRAPEND', '--', 'ARROW_POINT', 'ARROW_CIRCLE', 'ARROW_CROSS', 'ARROW_OPEN', 'DOTTED_ARROW_POINT', 'DOTTED_ARROW_CIRCLE', 'DOTTED_ARROW_CROSS', 'DOTTED_ARROW_OPEN', '==', 'THICK_ARROW_POINT', 'THICK_ARROW_CIRCLE', 'THICK_ARROW_CROSS', 'THICK_ARROW_OPEN', 'PIPE', 'STYLE', 'LINKSTYLE', 'CLASSDEF', 'CLASS', 'CLICK', 'DOWN', 'UP', 'DEFAULT', 'PCT', 'NUM', 'COMMA', 'ALPHA', 'COLON', 'MINUS', 'BRKT', 'DOT', 'TAGSTART', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', 'UNDERSCORE', got 'STR'
```
thanks for your time

**Comment by GDFaber** [comment] 2019-12-11 10:44
It also seems like ```'``` is transformed into ```"``` somehow in the html code, which is a problem. Is it also due to auto-formatting?

Should look like this: ```DIR("<img src='https://iconscout.com/ms-icon-310x310.png'; width='30' />")```,
but that doesn't fit the error message ```...ms-icon-310x310.png" width="30">")```.

**Comment by GDFaber** [comment] 2020-02-17 00:25
To be honest, I wouldn't consider this a problem being directly related to mermaid. I just tried the [example in the live-editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkRJUihcIjxpbWcgc3JjPSdodHRwczovL2ljb25zY291dC5jb20vbXMtaWNvbi0zMTB4MzEwLnBuZycgd2lkdGg9JzMwJyAvPlwiKVxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQiLCJzZWN1cml0eUxldmVsIjoibG9vc2UiLCJmbG93Y2hhcnQiOnsiaHRtbExhYmVscyI6dHJ1ZX19fQ) and it works for release 8.4.7 as well.

Hi @waterdrop01, I'm closing this issue. Feel free to open a new one if it turns out to be a problem caused by mermaid. Thank you for reaching out.

**Closed by GDFaber** 2020-02-17 00:25 UTC
Labels: Type: Other
