### ISSUE TITLE
Some of the Docs code samples are really hard to read.

### ISSUE THREAD

**Issue by jocfico** [mermaid-js/mermaid#5022] opened 2023-11-08 08:38 UTC
### Description

When I visit certain pages in the documentation:
e.g
https://mermaid.js.org/syntax/c4.html
https://mermaid.js.org/syntax/quadrantChart.html
https://mermaid.js.org/syntax/mindmap.html

Then the code samples feature really pale text that is hard to distinguish from the background colors.
Using the latest Chrome and Firefox on Mac.

### Steps to reproduce

Visit the linked pages. Some other pages are better but many are like the screenshot attached.

### Screenshots

<img width="726" alt="code-sample-1" src="https://github.com/mermaid-js/mermaid/assets/40295130/d6f9692f-106f-414a-82d0-fc4c3bcbd7c9">

### Setup

- Mermaid version: Current Mermaid.js.org website
- Browser and Version: Chrome, Firefox, latest, Mac

**Comment by Yokozuna59** [comment] 2023-11-08 16:47
Hi @jocfico, thanks for reporting the issue, it should be resolved in https://github.com/mermaid-js/mermaid/pull/4924.
Closing as duplicate of https://github.com/mermaid-js/mermaid/issues/4971.

**Closed by Yokozuna59** 2023-11-08 16:47 UTC
Labels: Type: Bug / Error, Status: Triage

**Comment by jocfico** [comment] 2023-11-08 19:08
Thanks @Yokozuna59 and sorry I didn't find the pre-existing issue(s)
