### ISSUE TITLE
change the Node Spacing in flowchart

### ISSUE THREAD

**Issue by AndrewScribner** [mermaid-js/mermaid#2099] opened 2021-05-29 12:19 UTC
How can the spacing between nodes be changed? In other words, the default connector length would change. Also, can an individual node be moved closer, thus appearing higher in rank than other parallel nodes.
By the way, I am using the flowchart diagram for a organizational chart.

**Comment by elf-pavlik** [comment] 2021-05-30 20:42
https://mermaid-js.github.io/mermaid/#/flowchart?id=minimum-length-of-a-link

Option above gives some degree of influence over the length of the link.

**Comment by Yokozuna59** [comment] 2023-08-03 20:52
duplicate of #2098

**Closed by Yokozuna59** 2023-08-03 20:52 UTC
Labels: Type: Other
