### ISSUE TITLE
Organizational Chart

### ISSUE THREAD

**Issue by AndrewScribner** [mermaid-js/mermaid#2103] opened 2021-05-31 14:31 UTC
Mermaid is one of the best and yet simplest that I have seen. Combination of both, that is. 
I am using the **flowchart** for an organizational chart, and it rocks. Would be great if there was a chart type for this.

**Comment by jgreywolf** [comment] 2023-04-05 16:24
Closing as duplicate of #2020

**Closed by jgreywolf** 2023-04-05 16:24 UTC
Labels: DUPE
