### ISSUE TITLE
Open arrow head

### ISSUE THREAD

**Issue by opyate** [mermaid-js/mermaid#1201] opened 2020-01-13 10:55 UTC
Open arrow heads to denote asynchronous messages as per https://en.m.wikipedia.org/wiki/Sequence_diagram

**Comment by opyate** [comment] 2020-01-13 11:01
Sorry, I initially searched "empty arrow head" and didn't find anything, but I see previous issues for "open arrow head".

**Comment by knsv** [comment] 2020-02-19 16:08
Here are the current syntax for arrows:

Type | Description
-- | --
-> | Solid line without arrow
--> | Dotted line without arrow
->> | Solid line with arrowhead
-->> | Dotted line with arrowhead
-x | Solid line with a cross at the end (async)
--x | Dotted line with a cross at the end (async)

The obvious syntax would be `->`. That one is occupied though and we cant make the existing diagrams change semantics after a mermaid release so we need something new. 

Some suggestions below from the top of my head. Anything better? If not, which should we pick? As indicated above, once release it will be set in stone.

Type | Description
-- | --
->>> | Solid line with open arrowhead
-->>> | Dotted line with open arrowhead

Type | Description
-- | --
-o | Solid line with open arrowhead
--o | Dotted line with open arrowhead

Type | Description
-- | --
-v | Solid line with open arrowhead
--v | Dotted line with open arrowhead

**Comment by knsv** [comment] 2020-02-19 16:09
A bit concerned with -o as maybe we want arrows ending with a circle one of these days...

**Comment by jgreywolf** [comment] 2020-02-19 17:36
I was looking at using -o for the _lolipop_ functionality in class diagrams...

**Comment by ganesshkumar** [comment] 2020-04-29 16:31
The usage of -v makes more sense among those three options

**Comment by Magicking** [comment] 2021-02-08 10:50
Seems to be a duplicate of #1528 fixed by https://github.com/mermaid-js/mermaid/pull/1854

**Comment by zthxxx** [comment] 2022-12-08 02:25
wanna get support this within flowchart

**Comment by jgreywolf** [comment] 2023-03-07 17:51
this was resolved with PR for #1528

**Closed by jgreywolf** 2023-03-07 17:51 UTC
Labels: Type: Enhancement, Status: Triage
