### ISSUE TITLE
Nodes ending in "call" break syntax

### ISSUE THREAD

**Issue by marcusmotill** [mermaid-js/mermaid#4245] opened 2023-03-24 19:19 UTC
### Description

This code works fine
```
graph TB;
    app_load["App Load"] --> any_api["Any API Call"];
    any_api --> any_api
```

```mermaid
graph TB;
    app_load["App Load"] --> any_api["Any API Call"];
    any_api --> any_api
```

This code breaks:
```
graph TB;
    app_load["App Load"] --> any_api_call["Any API Call"];
    any_api_call --> any_api_call
```

```mermaid
graph TB;
    app_load["App Load"] --> any_api_call["Any API Call"];
    any_api_call --> any_api_call
```

Only difference is `any_api` and `any_api_call`

### Steps to reproduce

Use live editor v10+ or v9, other versions not tested

### Screenshots

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/7673106/227619816-ce8c9223-cf7b-47e3-b353-8606ccc95d8f.png">

### Setup

- Mermaid version: 10, 9
- Browser and Version:Chrome

**Comment by joshchngs** [comment] 2023-06-15 11:49
Repro on v9.4.3

**Comment by nirname** [comment] 2023-07-11 14:21
If you put a semicolon after the line, it will work
This one works:
```
graph TB;
    test-->test_call;
    call;
```
```mermaid
graph TB;
    test-->test_call;
    call;
```

This one does not:
```
graph TB;
    test-->test_call;
    call
```
Should it work too?

**Comment by ibrahimWassouf** [comment] 2023-07-16 03:43
This is a duplicate of #2135, technically speaking. I'm working on it!

**Comment by nirname** [comment] 2023-07-16 12:21
This is a duplicate of #2495 too

**Comment by nirname** [comment] 2023-07-16 12:27
Please refer to this one #2135, I am closing it, because they share similar problem

**Closed by nirname** 2023-07-16 12:27 UTC
Labels: Type: Bug / Error, Status: Approved, Graph: Flow, Area: Development, Internals: Parser
