### ISSUE TITLE
Support for simple bar and line charts

### ISSUE THREAD

**Issue by JaneX8** [mermaid-js/mermaid#4773] opened 2023-08-25 13:02 UTC
I would really love to see support for simple line charts and bar charts as well. As far as I know there is no Mermaid like text-based implementation that already does this. It would be a great addition to tools such as Joplin, that already uses Mermaid.

```
bar
    title Bar Chart Example
    xtitle Categories
    ytitle Values
    "Category 1" : 10
    "Category 2" : 20
    "Category 3" : 15
    "Category 4" : 30
    "Category 5" : 25
```

```
line
    title Line Chart Example
    xtitle Time
    ytitle Values
    xFormat %Y-%m-%d
    "2023-01-01" : 10
    "2023-02-01" : 20
    "2023-03-01" : 15
    "2023-04-01" : 30
    "2023-05-01" : 25
```

**Comment by Yokozuna59** [comment] 2023-08-25 13:16
It's a duplicate of #4269, and it's being developed in #4413.

**Closed by Yokozuna59** 2023-08-25 13:16 UTC
Labels: Status: Triage
