### ISSUE TITLE
[Class Diagram] Bug with type with multiple generic parameters in type with multiple generic parameters

### ISSUE THREAD

**Issue by ArchiDog1998** [mermaid-js/mermaid#5857] opened 2024-09-13 02:32 UTC
### Description

Hi I am trying to create a type like this `Dictionary<double, Dictionary<double, Curve>>`. And this is what I got.
```
classDiagram
class Foo{
	- Dictionary~double, Dictionary~double, Curve~~ curves
}
```

``` mermaid
classDiagram
class Foo{
	- Dictionary~double, Dictionary~double, Curve~~ curves
}
```

But I might expect this to be like this. (learned from https://github.com/mermaid-js/mermaid/issues/3188#issuecomment-1505927730)

``` mermaid
classDiagram
class Foo{
	- Dictionary&lt;double, Dictionary&lt;double, Curve>> curves
}
```

Is that a bug?

### Steps to reproduce

Input things like this:
```
classDiagram
class Foo{
	- Dictionary~double, Dictionary~double, Curve~~ curves
}
```

``` mermaid
classDiagram
class Foo{
	- Dictionary~double, Dictionary~double, Curve~~ curves
}
```

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

**Comment by jgreywolf** [comment] 2024-09-13 18:08
Closing as duplicate of #4937

**Closed by jgreywolf** 2024-09-13 18:08 UTC
Labels: Type: Bug / Error, Status: Triage
