### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by prtuson** [mermaid-js/mermaid#1020] opened 2019-10-21 17:13 UTC
**Describe the bug**
When loading mermaid I am getting the error Uncaught SyntaxError: Unexpected token < reported by the browser and then mermaid cannot be found.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install mermaid.min.js from unkpg (8.4.0) in this case
2. Add <script src='mermaid.min.js'></script>
3. Load up to webserver
4. Open up in web browser and observe console log.

**Expected behaviour**
Should load without error

**Screenshots**
If applicable, add screenshots to help explain your problem

Screenshot shows error detail from Chromium console.

![Screenshot from 2019-10-21 18-08-32](https://user-images.githubusercontent.com/11800560/67226950-1769e680-f42e-11e9-84aa-6354a04d7505.png)

**Desktop (please complete the following information):**
 - OS: Debian Linux Testing
 - Browser: Chromium, Firefox, Web and Opera
 - Version: latest

**Additional context**
I have put a If file exists around the script code to ensure that it it is not a Not Found error.

I have been using Mermaid without significant problems on desktops and mobile phones for several years now so what am I doing wrong here?

**Comment by chris579** [comment] 2019-10-21 17:33
Does the console provide a stack trace?

**Comment by Dunning-Kruger** [comment] 2019-10-21 18:02
Hello, Peter, we appreciate the report!

As it is right now, it's impossible for us to reproduce the issue. 
Could you provide your resulting HTML page, its source code or anything else?

**Comment by prtuson** [comment] 2019-10-21 19:14
I am using mermaid.min.js 4.2.6 on my mobile phone application, I downloaded that using npm. It is 726kB in size as is declared on UNPNG.

I downloaded the mermaid.min.js direct from UNPKG and it was 2.1MB is size. It starts with an html declaration as:
<!DOCTYPE html><html lang="en"><head><script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-140352188-1"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-140352188-1');</script> ...

The same version loaded using npm starts with:

!function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e():"function"==typeof define&&define.amd?define([],e):"object"==typeof exports?exports.mermaid=e():t.mermaid=e()}(window,function(){return function(t){var e={} ...

So, I think that the html declaration is causing the problem. That means that I am downloading it incorrectly for my website. Currently I click with right mouse button and save link as ... as I have always done.

How should I be downloading it?

**Comment by Dunning-Kruger** [comment] 2019-10-21 19:54
For details on how to use UNPKG you can check out [their docs](https://unpkg.com/).

If you don't want to link to their CDN directly, you have to download the raw file, not their HTML page (which is what you are doing by right clicking and "save link as...").

**Comment by GDFaber** [comment] 2020-04-04 14:29
Hi @prtuson, as there was no further conversation since October, I consider the problem fixed by downloading the contents as @Dunning-Kruger suggested. I'm closing this issue, if I'm mistaken and you need additional support on the topic, please feel free to open a new issue.

**Closed by GDFaber** 2020-04-04 14:29 UTC
Labels: Type: Other
