### ISSUE TITLE
FR: Generate Hierarchy Diagram from Markdown List 

### ISSUE THREAD

**Issue by DarkTrick** [mermaid-js/mermaid#3037] opened 2022-05-14 00:45 UTC
### Is your feature request related to a problem? Please describe
*Problem*
Mermaid syntax can become very wordy or difficult to read.

*Background*

- Wordy: [Previous nodes have to be stated explicitly by name.](https://mermaid-js.github.io/mermaid/#/?id=flowchart)
- Difficult to read: Mermaid `&` syntax for expressing many nodes does not support line breaks

I have many markdown documents describing dependencies or hierarchies in a markdown-list format like the following:
```
- House
  - Kitchen
    - chair
    - table  
  - Living room
    - chair
    - table
  - Bathroom
     - bath tub
     - toilette 
```
To translate the into mermaid so a diagram can be generated, I end up with
1. very long lines connecting nodes via `&` ( `House --> Kitchen & Living room & Bathroom`)
2. or I need a lot redundancy by repeatedly restating the name of a node.

### Describe the solution you'd like
I'd like to create this: 
<img width="202" alt="image" src="https://user-images.githubusercontent.com/46980694/168404249-78181006-ac90-4287-9dab-ebc9370fce88.png">
from this:
```
- A
  - B
  - C
  - D
```

**Comment by knsv** [comment] 2022-08-21 09:10
This is very close to my the syntax for mindmaps that I am working on:
```
   root[The root]
      Child1
      child2(Child2)
        Other
      Child3
        GrandChild1
          sc1
          sc2
          sc3
        GrandChild2
```

We should do this. There are more diagrams that could use the syntax like wbs diagrams and org charts.

**Comment by KameronKales** [comment] 2023-03-02 11:25
Id love this feature as well

**Comment by jgreywolf** [comment] 2023-08-27 23:14
Closing as duplicate of #3989 and #1360

**Closed by jgreywolf** 2023-08-27 23:14 UTC
Labels: Type: Enhancement
