### ISSUE TITLE
mermaid.js:23977 Error: <svg> attribute viewBox: Expected number, "0 0 -Infinity -Infin…"

### ISSUE THREAD

**Issue by jockthekiwi** [mermaid-js/mermaid#1340] opened 2020-04-08 02:41 UTC
**Describe the bug**
We have added MermaidJS into an application and are allowing users to add the MermaidJS text against a User Story. When viewing an HTML page with the diagram we get the error for State Diagrams and Pie Charts. All other diagrams present correctly using the examples from the Live Editor

**To Reproduce**
View a chart with a PieChart or State Diagram. Have attached HTML files. The State diagram produces the error

**Example Files**
[Mermaid-Flow.txt](https://github.com/mermaid-js/mermaid/files/4447908/Mermaid-Flow.txt)
[Mermaid-State.txt](https://github.com/mermaid-js/mermaid/files/4447910/Mermaid-State.txt)

**Expected behavior**
The diagram should display without an error

**Screenshots**
![brave_HRfFJFnqxW](https://user-images.githubusercontent.com/2080637/78738769-c97a7800-79a6-11ea-9858-00e56b78e053.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Brave, Chrome

**Additional context**
Have mermaid.min.js as the script. 

This is the only Mermaid file I have downloaded.

Downloaded this last week

**Comment by lancerXXXX** [comment] 2020-04-19 15:02
the same problem

**Comment by GDFaber** [comment] 2020-05-17 16:26
Hi @jockthekiwi, can you check if this is still an issue in mermaid 8.5.1?

**Comment by GDFaber** [comment] 2020-07-28 17:37
I'm closing this issue since I cannot reproduce the problem in mermaid 8.6.4, feel free to report if the error still shows up so we can reopen the issue.

**Closed by GDFaber** 2020-07-28 17:37 UTC
Labels: Status: Triage, Type: Bug / Error
