### ISSUE TITLE
Class diagram classifiers to not work with methods with special characters

### ISSUE THREAD

**Issue by sambostock** [mermaid-js/mermaid#3424] opened 2022-09-06 05:01 UTC
**Describe the bug**

Many languages sometimes allow special characters in method names. For example, Ruby uses:
- the `?` suffix for "predicate methods"
- the `!` suffix for "dangerous methods"

These are not well supported, and in particular cannot be combined with static and abstract method classifiers.

**To Reproduce**

Define a method using special characters, such as `?` or `!`.

**Expected behavior**

The method name should render like any other, with the correct formatting.

It is acceptable for it to be required to surround the method name with backticks, similarly to how `::` support (Ruby's namespacing/nesting syntax) was added for class names by wrapping them in backticks.

**Code Sample**

<table><tr><th>Code</th><th>Rendered</th><th>Live</th></tr><tr><td>

```
classDiagram
  class `Example::Ruby::Class` {
    normal()
    predicate()?
    dangerous!()?
    static_normal()$
    static_predicate?()$
    static_dangerous!()$
  }
```

</td><td>

```mermaid
classDiagram
  class `Example::Ruby::Class` {
    normal()
    predicate()?
    dangerous!()?
    static_normal()$
    static_predicate?()$
    static_dangerous!()$
  }
```

</td><td>

[![](https://mermaid.ink/img/pako:eNpdkEsOwjAMRK8SLBat1BNkwwJ6AdhGoiYxJSKfKh-JCnF3-qMCdp7x-GnkJ0ivCDhIgzEeNLYBrXCMTZo19QNtZ4jzY770nO9Ht2HPMcGY88GiKcpZdYGUlpioKHezo9C1FHyOm9WKCZOW58_l9sddCbv_zTdp2rygAksDRKuh_NRHQLqRJQF8GBWGuwDhxlzu1MCslU4-AL-iiVQB5uRPvZPAU8j0CS0PWFKvN95MX0E)](https://mermaid.live/edit#pako:eNpdkEsOwjAMRK8SLBat1BNkwwJ6AdhGoiYxJSKfKh-JCnF3-qMCdp7x-GnkJ0ivCDhIgzEeNLYBrXCMTZo19QNtZ4jzY770nO9Ht2HPMcGY88GiKcpZdYGUlpioKHezo9C1FHyOm9WKCZOW58_l9sddCbv_zTdp2rygAksDRKuh_NRHQLqRJQF8GBWGuwDhxlzu1MCslU4-AL-iiVQB5uRPvZPAU8j0CS0PWFKvN95MX0E)

</td></tr></table>

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: Mermaid.live 9.1.6

---

Similar to https://github.com/mermaid-js/mermaid/issues/1635

**Comment by jgreywolf** [comment] 2023-03-10 17:34
Closing as duplicate of #1635

**Closed by jgreywolf** 2023-03-10 17:34 UTC
Labels: Type: Bug / Error, Status: Triage
