### ISSUE TITLE
Programmatically interacting with Mermaid diagrams

### ISSUE THREAD

**Issue by abelardolg** [mermaid-js/mermaid#3241] opened 2022-07-18 14:11 UTC
Hi there.
I wonder if there is any way to interact with Mermaid diagrams by clicking over them.
My goal is clear:
I would like to programmatically generate a state diagram according to states stored inside my database.
Each time I click on a state, I would like to send a post request to my Symfony controller to act according to that click and show an appropriate web page and dinamically stylize that state with a CSS style.
Thanks.

**Comment by sidharthv96** [comment] 2022-10-08 11:43
State diagram doesn't support interaction right now. 

https://mermaid-js.github.io/mermaid/#/classDiagram?id=interaction

PRs are welcome to add support.

**Comment by yurtsiv** [comment] 2022-10-08 21:14
Hi @sidharthv96 :wave:
I would be happy to try implementing it but first wanna know why it's not supported. Is there some super difficult parsing problem or you just didn't have time for it yet?

**Comment by sidharthv96** [comment] 2022-10-09 02:23
@yurtsiv The state diagram was added a while back, I wasn't involved during that time. 

But I think interaction support was simply not added. It should be relatively straightforward to refer flowchart/classdiagram code to add support. 

You'll mainly have to make changes in the jison file, db and renderer. (I think)

**Comment by sidharthv96** [comment] 2022-10-09 12:01
Related https://github.com/mermaid-js/mermaid/issues/1139

**Comment by yurtsiv** [comment] 2022-10-09 18:14
I'll try to tackle this

**Comment by jgreywolf** [comment] 2023-01-26 18:06
Closing as Duplicate of #1139

**Closed by jgreywolf** 2023-01-26 18:06 UTC
Labels: Area: Development, Graph: State, Status: Awaiting PR, hacktoberfest
