### ISSUE TITLE
The previous graph is also loaded in the next graph in Vue.js

### ISSUE THREAD

**Issue by leteu** [mermaid-js/mermaid#3312] opened 2022-08-10 09:33 UTC
![image](https://user-images.githubusercontent.com/77822996/183867382-32d67b9d-9958-4446-987f-6a574ac126ba.png)

I've created a component that calls Mermaid, but it's still saving the old graph. Did i something wrong?

mermaid version : v9.1.4

```vue
<template>
	<Mermaid v-model="test1" />
    <Mermaid v-model="test2" />
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import Mermaid from 'src/components/Mermaid'

export default defineComponent({
  name: 'IndexPage',
  components: {
    Mermaid
  },
  setup () {
    const test1 = `sequenceDiagram
      participant John
    `
    const test2 = `sequenceDiagram
      participant Alice
    `

    return {
      test1,
      test2
    }
  }
});
</script>
```

//Mermaid.vue Component
```ts
import { defineComponent, h, ref, onMounted } from "vue";
import mermaid from 'mermaid'

export default defineComponent({
  props: {
    modelValue: {
      type: String,
      required: true
    }
  },
  setup(props, { slots }) {
    const innerHTML = ref('');
    const needsUniqueId = "render" + (Math.floor(Math.random() * 10000)).toString();

    onMounted(() => {
      mermaid.mermaidAPI.render(needsUniqueId, props.modelValue, (html) => {
        innerHTML.value = html
      })
    });

    return () => h(
      'div',
      {
        innerHTML: innerHTML.value
      },
    )
  }
});
```

**Comment by hrgui** [comment] 2022-08-10 15:18
This is the same as #3305.

**Comment by ashishjain0512** [comment] 2022-08-18 16:18
Hey @leteu

Could you please check whether the issue is reproducible in version 9.1.5 ? A fix regarding this issue was released with the new version, and you should not be facing this anymore.

If you still see this issue, kindly report back, and we will be happy to dig deeper.

**Closed by ashishjain0512** 2022-08-18 16:18 UTC
Labels: Type: Other, Status: Triage
