### ISSUE TITLE
Support for double arrow links?

### ISSUE THREAD

**Issue by decentral1se** [mermaid-js/mermaid#457] opened 2017-01-12 15:47 UTC
Something like `A[first node] <--> B[second node]`?

Does it already exist?

**Comment by knsv** [comment] 2017-01-19 18:26
No, it has been discussed though. Problem with the syntax is that <---> will be interpreted as a tag by the browser so something else is required. See issue #123.

**Comment by lwm** [comment] 2017-01-19 19:06
Ah! Missed that one. Will close this off in favor of #123. Thanks!

**Comment by knsv** [comment] 2019-06-28 07:54
Reopening this one as #123 refers to class diagrams where this is implemented

**Comment by jgreywolf** [comment] 2019-09-27 21:33
I am still interested in this one.  Is there any chance of this support being added?

**Comment by asbjornu** [comment] 2019-09-28 20:25
Aren't all tags escaped already? I can write `<xyz>` pretty much everywhere in a sequence diagram and it gets represented as text, not as a tag. Does this encoding issue only apply to arrows?

**Comment by jgreywolf** [comment] 2019-10-01 17:42
Im a little confused on this one.  In looking at the source it _looks_ like this is already defined.  I am still going through the code to better understand exactly what is happening though, so I may be missing something

**Comment by Dunning-Kruger** [comment] 2019-10-01 17:45
@jgreywolf As you can see in the issue, there's some work already done in the "grammar" side of it here: https://github.com/knsv/mermaid/commit/40d10ea7413145836d26a8a7b3420fe7905993f8

Note that this is currently assigned to @knsv. Safe to assume that this is being worked on already by him.

**Comment by jgreywolf** [comment] 2019-10-01 17:48
Yes, I was just looking at #123.  Should this issue be closed, and pointed to that one instead?

**Comment by knsv** [comment] 2019-10-08 20:42
Some work has been made for this issue. The grammar is done but the renderer is not complete and that will take a while. The problem is that the library we use for rendering flowcharts does not support this. So in order to complete this issue we will need to do all the rendering "in house" which is better in the long run. Till will also open up for more arrow types (see class diagrams).

This will be put into pause for that refactoring to start.

**Comment by vantoan8x** [comment] 2020-06-11 01:56
Dear @knsv,

is this function complete?
A --> B
A <-- B
A <--> B

A --o B
A o-- B
A o--o B

A --x B
A x-- B
A x--x B

May I know when you release this features?
Do you need any help?

Regards.
Tom.

**Comment by jgreywolf** [comment] 2020-08-12 19:38
@vantoan8x support has been added to flowcharts for double arrow links (beta). See [documentation](https://mermaid-js.github.io/mermaid/#/flowchart?id=beta-multi-directional-arrows)

**Comment by vantoan8x** [comment] 2020-08-13 01:35
@jgreywolf It great, Thank you so much.

**Closed** 2020-08-13 17:10 UTC
Labels: Area: Development, Status: Approved, Type: Enhancement
