### ISSUE TITLE
Display empty class as a square/other form

### ISSUE THREAD

**Issue by nicola-lunghi** [mermaid-js/mermaid#3302] opened 2022-08-08 10:36 UTC
Hi,
I have the following graph:
```mermaid
classDiagram
    NotEmptyClass ..> emptyClass
    class NotEmptyClass {
          +myproperty
          +myfunction()
    }
    class emptyClass {
    }
```
I would like to remove the two lines from the emptyClass and to display it as a simple rectangle.
It is possible?
Can I also apply other shapes to it ? (from the flowchart, for example a circle)

like

```mermaid
flowchart
    NotEmptyClass --> id2((emptyClass ))
```

Thanks,
Nick

**Comment by jgreywolf** [comment] 2023-03-17 17:41
Duplicate of #3139

**Closed by jgreywolf** 2023-03-17 17:41 UTC
Labels: Type: Enhancement, Status: Approved, Graph: Class
