### ISSUE TITLE
Add support of "LaTeX" in the form of MathJax

### ISSUE THREAD

**Issue by Minderer** [mermaid-js/mermaid#2267] opened 2021-08-25 09:26 UTC
Hello
Mermaid have incredible potential for STEM – not super useful for diagrams with mathematical symbolism.
If you add LaTeX support, then a significant amount of this potential is released on the STEM community.
Mermaid will get immortalised if this happens.
Best regards

**Comment by Elaws** [comment] 2022-02-20 12:39
This is a great idea. Any news for that FR ?

**Comment by sunt05** [comment] 2022-11-20 20:29
related #2776

**Comment by DaveJarvis** [comment] 2022-12-14 22:04
This can probably be closed as a duplicate of #2776

**Comment by Yokozuna59** [comment] 2023-08-09 21:22
duplicate of #2776

**Closed by Yokozuna59** 2023-08-09 21:22 UTC
Labels: Type: Enhancement, Status: Triage
