### ISSUE TITLE
Click "#id" do not work on flowchart with Markdown

### ISSUE THREAD

**Issue by wojtek717** [mermaid-js/mermaid#2770] opened 2022-02-23 08:06 UTC
**Describe the bug**
The `click "#id" `does not work when you use it in Makrdown using the [Markdown Preview Mermaid Support](https://github.com/mjbvz/vscode-markdown-mermaid#markdown-preview-mermaid-support) to jump to a particular section on the current page. Instead of jumping to the given section, the about:blank page appears.

**To Reproduce**
1. Open VS Code and install [Markdown Preview Mermaid Support](https://github.com/mjbvz/vscode-markdown-mermaid) extension
2. Add to your markdown code the id section: `# id`
3. Add to your markdown code mermaid flowchart
```
   flowchart TB
     A1[Click me]

     click A1 "#id"
   ```
or
   ```
   flowchart TB
     A1[Click me]

     click A1 href "#id"
   ```
4. Click A1 node
5. about:blank page appears.

**Expected behavior**
After clicking on A1, the page is set to the #id section.

**Code Sample**
```
   flowchart TB
     A1[Click me]

     click A1 "#id"
   ```
or
   ```
   flowchart TB
     A1[Click me]

     click A1 href "#id"
   ```
**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: safari/chrome
 - Version: 14.1.1

**Comment by jgreywolf** [comment] 2023-10-04 23:19
Closing as duplicate of #2233

**Closed by jgreywolf** 2023-10-04 23:19 UTC
Labels: Type: Bug / Error, Status: Triage
