### ISSUE TITLE
Update NPM readme

### ISSUE THREAD

**Issue by klemmchr** [mermaid-js/mermaid#1046] opened 2019-11-02 15:37 UTC
As the Readme got reworked with #1045 it also needs to be updated on [npm](https://www.npmjs.com/package/mermaid). The images are broken currently because they are referenced by a relative path. They might need to be replaced with an absolute url.

**Comment by chris579** [comment] 2019-11-02 17:12
Maybe we also should automate that. A little workflow updating the readme on npm when the readme in the repo changes.

**Comment by NeilCuzon** [comment] 2020-03-09 00:04
hi guys! I've recently contributed to the docs, including some recent edits for the README.md, for mermaid and I would want to help out with this issue as well. 

however, I don't have any real experience with updating the documentation for npm. 
Point me in the right direction and I'll work on it.

**Comment by Dunning-Kruger** [comment] 2020-03-09 12:31
@NeilCuzon Thank you for the good intentions but the issue is already assigned to someone with permission on NPM.

**Closed** 2021-02-01 19:06 UTC
Labels: Area: Documentation, Status: Approved, Type: Other
