### ISSUE TITLE
Running Without Chromium Dependencies

### ISSUE THREAD

**Issue by pb-seiso** [mermaid-js/mermaid#1494] opened 2020-06-22 15:21 UTC
I'm attempting to install and run Mermaid in a light-weight Docker container running Ubuntu 20.04.

When interacting with the container and running `mmdc`, I'm receiving the following error originating from Puppeteer: `UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!`
Full error: [runtime_error.txt](https://github.com/mermaid-js/mermaid/files/4814005/runtime_error.txt)

From the package.json, Puppeteer is a dev dependency only. When installing Mermaid and Mermaid CLI using `yarn add`, I do not specify inclusion of development dependencies.

```
ARG MERMAID_VERSION="8.5.2"
ARG MERMAID_CLI_VERSION="8.5.1-2"
RUN yarn add mermaid@${MERMAID_VERSION} \
             @mermaid-js/mermaid-cli@${MERMAID_CLI_VERSION}
```

The following entry is in the `yarn.lock`, which does not specify Puppeteer as a dependency:
```
mermaid@8.5.2:
  version "8.5.2"
  resolved "https://registry.yarnpkg.com/mermaid/-/mermaid-8.5.2.tgz#0f1914cda53d4ea5377380e5ce07a38bef2ea7e8"
  integrity sha512-I+s+8/RzlazF3dGOhDUfU/ERkUV4zfIlTWb3703jNx+2lfACs+4AdY9ULQaw6BPWzW3gB+XlXFOOX/m/vqujIA==
  dependencies:
    "@braintree/sanitize-url" "^3.1.0"
    crypto-random-string "^3.0.1"
    d3 "^5.7.0"
    dagre "^0.8.4"
    dagre-d3 "^0.6.4"
    entity-decode "^2.0.2"
    graphlib "^2.1.7"
    he "^1.2.0"
    minify "^4.1.1"
    moment-mini "^2.22.1"
    scope-css "^1.2.1"
```

I've tried adding the `--prod` or `--production=true` flags to to the `yarn add`, but `mmdc` still fails with the same issue. It seems the only way to avoid the error is to include all of the many Chromium dependencies that Puppeteer requires, and then it runs successfully. 

Is there any way to avoid pulling in these dependencies just to run `mmdc`? I'm unfamiliar with yarn, so please let me know if I've missed something.

**Comment by VincentTam** [comment] 2020-08-31 09:43
> I'm attempting to install and run Mermaid in a light-weight Docker container running Ubuntu 20.04.

It's better to choose Alpine Linux if you want your Docker image to be lightweight.

**Comment by JonZeolla** [comment] 2020-10-13 02:29
Any update on this?

**Comment by pb-seiso** [comment] 2020-12-07 14:34
Has there been any work done on this? Mermaid isn't currently viable for my image with the extra 600 MB in dependencies that get pulled.

**Comment by DanInProgress** [comment] 2022-11-21 14:14
This has definitely been a pain-point for me, and looks like some new discussion has opened up about this on  #3650 , 
if I have time I'm going to try to experiment with this some time in the next month.  (maybe too little, too late for your use)

Seems like this issue has gone a bit stale, and is duplicated by discussion on #3650 , so might be worth closing this and continuing conversation over there? @pb-seiso

**Comment by jgreywolf** [comment] 2023-01-26 19:58
Closing as duplicate of #3650

**Closed by jgreywolf** 2023-01-26 19:58 UTC
Labels: Type: Other, Status: Triage, Area: DevOps
