### ISSUE TITLE
Entity Relation Chart do not support non-ascii character

### ISSUE THREAD

**Issue by peter-jerry-ye** [mermaid-js/mermaid#1478] opened 2020-06-15 22:12 UTC
**Describe the bug**
Entity Relation Chart do not support non-ascii character

**To Reproduce**
1. Go to [Mermid live editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgQVtDaHJpc3RtYXNdIC0tPnxHZXQgbW9uZXl8IEIoR28gc2hvcHBpbmcpXG4gIEIgLS0-IEN7TGV0IG1lIHRoaW5rfVxuICBDIC0tPnxPbmV8IERbTGFwdG9wXVxuICBDIC0tPnxUd298IEVbaVBob25lXVxuICBDIC0tPnxUaHJlZXwgRltmYTpmYS1jYXIgQ2FyXVxuXHRcdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)
2. Click on 'ER Diagram'
3. Replace any of 'CUSTOMER' or 'DELIVERY-ADDRESS' or 'has' by a non-ascii word, like '顾客', 'à'

**Expected behavior**
No syntax error

**Screenshots**
![image](https://user-images.githubusercontent.com/16731997/84711091-d21e9a00-af65-11ea-9783-ec0011f48be5.png)

**Desktop (please complete the following information):**
 - OS: Win10 1909
 - Browser: Edge chromium & firefox
 - Version: 8.5.2

**Comment by sidharthv96** [comment] 2023-09-16 09:42
We could add support to labels like we have in class and flow diagrams. 
Double quoted strings will support unicode.

**Comment by aloisklink** [comment] 2024-02-28 14:48
I believe this is a duplicate of #3171, and it's already been fixed as part of https://github.com/mermaid-js/mermaid/pull/3516.

However, attribute types/names still don't support non-ascii characters. However, attribute comments do, see below:

````markdown
```mermaid
erDiagram
    "🌋 volcano" ||--o{ "Hiking Trail 🥾" : "contains 🧭"
    "🌋 volcano" {
        string name "name: 名"
        float height "my 📈"
        string sector
    }
```
````

renders as

```mermaid
erDiagram
    "🌋 volcano" ||--o{ "Hiking Trail 🥾" : "contains 🧭"
    "🌋 volcano" {
        string name "name: 名"
        float height "my 📈"
        string sector
    }
```

**Closed by aloisklink** 2024-02-28 14:48 UTC
Labels: Type: Bug / Error, Contributor needed, Status: Approved, Graph: Entity Relationship, Internals: Parser
