### ISSUE TITLE
Line/Bar diargams wanted

### ISSUE THREAD

**Issue by popovoleksandr** [mermaid-js/mermaid#1970] opened 2021-04-01 02:22 UTC
Thanks for so beautiful project.
Is it possible to add simple diagrams like line or bar? I don't know why it is not here but it would be really helpful.

**Comment by Yokozuna59** [comment] 2023-06-01 09:18
They're currently working on it here #4269 and discussing the grammar.

You could mark this issue as resolved since it's currently a duplication.

Or if you can @sidharthv96.

**Comment by sidharthv96** [comment] 2023-06-02 06:33
Thanks @Yokozuna59, closed as duplicate of https://github.com/mermaid-js/mermaid/issues/4269

**Closed** 2023-06-02 06:33 UTC
Labels: duplicate

**Comment by Yokozuna59** [comment] 2023-06-03 10:46
@sidharthv96 shouldn't be closed as `resolved` with `DUPE` label?
