### ISSUE TITLE
Wrong rendered class diagram

### ISSUE THREAD

**Issue by j4nos** [mermaid-js/mermaid#1215] opened 2020-01-23 11:06 UTC
This is the diagram:

```mermaid
classDiagram
class Auditorium{
  String name
}
class PriceSector{
  String price
}
class Sector{
  String name
}
class Seat{
  Float x
  Float y
}
class Event{
  String fbId
  Bool inProgress
  String name
  String purpose
  Int? numberOfVisitorsWillSeeEachTestPrice
  Int? estimatedNumberOfVisitors
  Int? auditoriumId
  String? auditoriumName
  [String]? pricesAdditional
  [String]? pricesPerSector
  [String: String] pricesAdditionalPerTempUser
}
class User{
  String fbId
}
class Ticket{
 String creationDate
}
Auditorium *-- PriceSector
PriceSector *-- Sector
Sector *-- Seat
Event --> Auditorium
Ticket --> User
Ticket --> Seat
Ticket --> Event
```

And rendered like this:

<img width="660" alt="Képernyőfotó 2020-01-23 - 12 05 27" src="https://user-images.githubusercontent.com/11924475/72979507-c5dc4980-3dd8-11ea-8434-67b62f8467bf.png">

**Comment by jgreywolf** [comment] 2020-01-23 21:26
Adding example in live editor that better displays full picture (right side of diagram is getting cut off)

https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBBdWRpdG9yaXVte1xuICBTdHJpbmcgbmFtZVxufVxuY2xhc3MgUHJpY2VTZWN0b3J7XG4gIFN0cmluZyBwcmljZVxufVxuY2xhc3MgU2VjdG9ye1xuICBTdHJpbmcgbmFtZVxufVxuY2xhc3MgU2VhdHtcbiAgRmxvYXQgeFxuICBGbG9hdCB5XG59XG5jbGFzcyBFdmVudHtcbiAgU3RyaW5nIGZiSWRcbiAgQm9vbCBpblByb2dyZXNzXG4gIFN0cmluZyBuYW1lXG4gIFN0cmluZyBwdXJwb3NlXG4gIEludD8gbnVtYmVyT2ZWaXNpdG9yc1dpbGxTZWVFYWNoVGVzdFByaWNlXG4gIEludD8gZXN0aW1hdGVkTnVtYmVyT2ZWaXNpdG9yc1xuICBJbnQ_IGF1ZGl0b3JpdW1JZFxuICBTdHJpbmc_IGF1ZGl0b3JpdW1OYW1lXG4gIFtTdHJpbmddPyBwcmljZXNBZGRpdGlvbmFsXG4gIFtTdHJpbmddPyBwcmljZXNQZXJTZWN0b3JcbiAgW1N0cmluZzogU3RyaW5nXSBwcmljZXNBZGRpdGlvbmFsUGVyVGVtcFVzZXJcbn1cbmNsYXNzIFVzZXJ7XG4gIFN0cmluZyBmYklkXG59XG5jbGFzcyBUaWNrZXR7XG4gU3RyaW5nIGNyZWF0aW9uRGF0ZVxufVxuQXVkaXRvcml1bSAqLS0gUHJpY2VTZWN0b3JcblByaWNlU2VjdG9yICotLSBTZWN0b3JcblNlY3RvciAqLS0gU2VhdFxuRXZlbnQgLS0-IEF1ZGl0b3JpdW1cblRpY2tldCAtLT4gVXNlclxuVGlja2V0IC0tPiBTZWF0XG5UaWNrZXQgLS0-IEV2ZW50IiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0

**Comment by jgreywolf** [comment] 2020-01-23 21:31
Duplicate of #1058

**Comment by j4nos** [comment] 2020-01-24 10:13
So what can I do to increase viewport? :)

**Comment by jgreywolf** [comment] 2020-01-27 17:47
Closing as duplicate - I am starting to work on #1058 now

**Closed by jgreywolf** 2020-01-27 17:47 UTC
Labels: Status: Triage
