### ISSUE TITLE
Text is not rendered in nodes of flowchart with several commas

### ISSUE THREAD

**Issue by InAnYan** [mermaid-js/mermaid#5787] opened 2024-08-28 11:55 UTC
### Description

When I wrote a node with text in double quotes with several commas, the text is not rendered inside a node.

### Steps to reproduce

1. Run code sample

### Screenshots

![image](https://github.com/user-attachments/assets/fdb5be4f-5f94-4cd7-9da5-a3849ffb9d51)

### Code Sample

```text
flowchart TB
    githost["Github, Gitlab, BitBucket, etc."]
```

### Setup

- Mermaid version: 11.0.2
- Browser and Version: Firefox

**Comment by InAnYan** [comment] 2024-08-28 11:56
It seems this also breaks if I replace commas with semicolons

**Comment by InAnYan** [comment] 2024-08-28 11:57
Updating:

When you use **special characters** like comma, dot (dot is new), semicolon, and you type them **more than once**, the rendering breaks.

A **single** special character is fine

**Comment by jgreywolf** [comment] 2024-08-29 15:06
I believe that this may be a firefox only issue

**Comment by dolt** [comment] 2024-08-29 21:58
It's appears to be a Firefox issue and it isn't the number of commas, it fails to render the text if it's long enough to wrap.
```
flowchart TB
    example["This text is too long by one."]
```

**Comment by dolt** [comment] 2024-08-29 22:20
As a mitigation you can conditionally disable htmlLabels for Firefox user-agents.
```
    flowchart: {
        useMaxWidth: false,
        htmlLabels: !navigator.userAgent.includes('Firefox'), // text long enough to wrap is not rendering in Firefox
    },
```

**Comment by dolt** [comment] 2024-08-30 01:57
This issue looks to be a duplicate of #5785

**Closed** 2024-09-12 09:31 UTC
Labels: Type: Bug / Error, Status: Approved, Area: Development
