### ISSUE TITLE
ERD: <text> attribute y: Expected length, "NaN"

### ISSUE THREAD

**Issue by tessus** [mermaid-js/mermaid#1362] opened 2020-04-22 21:31 UTC
**Describe the bug**
When rendering an ERD, the following errors are shown in the console:

```
Error: <text> attribute y: Expected length, "NaN".
Error: <text> attribute y: Expected length, "NaN".
Error: <text> attribute y: Expected length, "NaN".
Error: <text> attribute y: Expected length, "NaN".
Error: <text> attribute y: Expected length, "NaN".
Error: <text> attribute y: Expected length, "NaN".
Error: <text> attribute y: Expected length, "NaN".
Error: <text> attribute y: Expected length, "NaN".
mermaid.min.js:31 Error: <text> attribute y: Expected length, "NaN".
(anonymous) @ mermaid.min.js:31
each @ mermaid.min.js:31
attr @ mermaid.min.js:31
(anonymous) @ mermaid.min.js:41
Ni @ mermaid.min.js:41
render @ mermaid.min.js:41
i @ mermaid.min.js:48
init @ mermaid.min.js:48
```

**To Reproduce**
1. Render the following ERD:

```
erDiagram
    ENTITY-1 !-!< ENTITY-2 : role
    ENTITY-1 ?-?< ENTITY-3 : role
```

**Expected behavior**
No errors in console

**Screenshots**
n/a

**Desktop (please complete the following information):**
Irrelevant

**Smartphone (please complete the following information):**
Irrelevant

**Additional context**
Mermaid 8.5.0

**Comment by spopida** [comment] 2020-04-23 07:59
Hi, and thanks for posting.  The syntax above was never actually released...instead I changed it to make it compatible with PlantUML ER syntax.  If you use the following, it should work:

```
erDiagram
    ENTITY-1 ||--|{ ENTITY-2 : role
    ENTITY-1 |o--o{ ENTITY-3 : role
```
You can also use dots instead of dashes to get dashed relationship lines

You can find fuller documentation here: [ER documentation](https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram)

I hope this helps.

**Comment by tessus** [comment] 2020-04-23 21:50
Thanks for the info.

Nope, same error with your example above.

**Comment by spopida** [comment] 2020-04-24 14:49
Hi - sorry you're still having this issue..I'm not sure how that's happening.  Have you tried this in the Live Editor, or are you calling the API?.  The screen shot below shows what I get in the Live Editor...

![image](https://user-images.githubusercontent.com/19526120/80225376-e7043e80-8642-11ea-9a59-8b00994e3b3f.png)

**Comment by tessus** [comment] 2020-04-25 03:11
Just open the console in the browser and you'll see the error.

**Comment by tessus** [comment] 2020-04-25 03:12
Although I've just noticed that the error message is now `Unexpected value NaN parsing y attribute.`

**Comment by spopida** [comment] 2020-04-28 11:40
OK - managed to reproduce this on Chrome, but not FF.  
- Can you confirm your browser / version please?  
- Also, for me it doesn't prevent rendering - is it the same for you?

Thanks

**Comment by tessus** [comment] 2020-04-28 23:28
I'm actually using Waterfox, which is a Firefox based browser without the telemetry.

There's no rendering issue, just the errors in the console. Actually the reason why I've opened the issue is another story:

We use Mermaid 8.4.6 in [Joplin](https://github.com/laurent22/joplin). Somebody opened a ticket and said that ERDs are not working. I found out that ERDs were added in 8.5.0 and updated Mermaid in a test branch and then I have noticed that I receive errors in the console, but only when it renders ERDs.
Thus I was rather reluctant to upgrade for good, since errors are never a good sign, even if the result is ok.

**Comment by spopida** [comment] 2020-04-29 09:24
OK, thanks for the info - that's useful to know.
I agree it's not good to have errors.  As the author of the new ERD functionality I will do my best to get it working smoothly.  Now that I can re-produce the problem I hope I can get to the bottom of it soon - please watch this space.  I will post an update when I have something useful to report.

**Comment by spopida** [comment] 2020-04-30 15:13
I found the issue which was caused by a fontSize config option being initialized to a string (e.g. '12px' instead of an integer.  This was used in simple positioning calcs, which then caused the y co-ordinate of entity labels to be set to 'NaN'.  Rendering was successful anyway, but the error created noise (and might trip up some browsers now or in the future).

I have fixed the issue in my fork and created a PR so that the fix is merged into the core code.  Barring surprises it should be included in the next release.  In the meantime, if your browser deals with it successfully, then I think it is safe to ignore it.

I have tested this on Chrome, Firefox, and Waterfox.  Thanks for reporting it.

**Closed** 2020-05-01 13:14 UTC
Labels: Type: Bug / Error
