### ISSUE TITLE
BUG: Scroll is not working in sidebar after refreshing

### ISSUE THREAD

**Issue by vk-0-7** [mermaid-js/mermaid#4902] opened 2023-10-04 06:07 UTC
### Description

when you try to scroll the sidebar of the page . the sidebar does not get scrolled instead the main content get scrolled. This only happens if you refresh the page with scrollbar e.g .- Docs page or tutorial page. if you jump from home page . then the scrollbar is working fine.

https://github.com/mermaid-js/mermaid/assets/77395813/512df712-7a3f-4f1d-8b11-66837d5e91b2

### Steps to reproduce

1. visit [mermaid](https://mermaid.js.org/intro/) .
2. scroll the sidebar.

### Screenshots

<img width="938" alt="Screenshot 2023-10-04 111807" src="https://github.com/mermaid-js/mermaid/assets/77395813/6c08de92-e13b-48df-a193-28d0e3479c98">

### Setup

- Mermaid version:
- Browser and Version: [Chrome, Edge, Firefox]

### Suggested Solutions

sidebar should be scrollable even after refreshing the page.

**Comment by harshul786** [comment] 2023-10-04 09:41
This is a serious issue I think 

https://github.com/mermaid-js/mermaid/assets/68487877/fdaf0d7e-dd7a-4102-8b53-e461a5f275d4

On macos, you can't even click a thing on the sidebar, nor you can scroll it.
[mermaid](https://mermaid.js.org/intro/)

**Comment by italomaia-bk** [comment] 2023-10-04 10:07
Scrolling and links do not work on **Chrome 117.0.5938.132** links and scrolling do not work. The problem is that there is a element in front of the sidebar and that is blocking access to it (clicks & scrolling).

This CSS rule `.VPContent[data-v-644df344]` is setting width to 100% and that is causing the issue. By removing it, things work again (not sure what will break due to that change, but it works fine for me).

**Comment by vk-0-7** [comment] 2023-10-04 12:26
> This is a serious issue I think
> 
>  Screen.Recording.2023-10-04.at.3.08.34.PM.mov 
> On macos, you can't even click a thing on the sidebar, nor you can scroll it. [mermaid](https://mermaid.js.org/intro/)

**Comment by huynhicode** [comment] 2023-10-30 02:05
This seems to have been resolved with the latest update to Docs.

Closing issue - please reopen if needed.  Thanks!

**Closed by huynhicode** 2023-10-30 02:05 UTC
Labels: Type: Bug / Error, Status: Triage
